// src/lib/mock-data.ts
// ═══════════════════════════════════════════════════
// PLUG.PK — MOCK DATA
// Development fixtures. Replace with API calls in a later phase.
// ═══════════════════════════════════════════════════

import type {
  CommunityPost,
  EVModel,
  EVService,
  OperatingHours,
  PlatformStats,
  Station,
} from './types'

// ─── Shared Operating-Hour Presets ───────────────────

const HOURS_24_7: OperatingHours = {
  is24Hours: true,
  monday: { open: '00:00', close: '23:59', isClosed: false },
  tuesday: { open: '00:00', close: '23:59', isClosed: false },
  wednesday: { open: '00:00', close: '23:59', isClosed: false },
  thursday: { open: '00:00', close: '23:59', isClosed: false },
  friday: { open: '00:00', close: '23:59', isClosed: false },
  saturday: { open: '00:00', close: '23:59', isClosed: false },
  sunday: { open: '00:00', close: '23:59', isClosed: false },
}

const HOURS_MALL: OperatingHours = {
  is24Hours: false,
  monday: { open: '10:00', close: '23:00', isClosed: false },
  tuesday: { open: '10:00', close: '23:00', isClosed: false },
  wednesday: { open: '10:00', close: '23:00', isClosed: false },
  thursday: { open: '10:00', close: '23:00', isClosed: false },
  friday: { open: '14:00', close: '23:00', isClosed: false },
  saturday: { open: '10:00', close: '00:00', isClosed: false },
  sunday: { open: '10:00', close: '00:00', isClosed: false },
}

const HOURS_BUSINESS: OperatingHours = {
  is24Hours: false,
  monday: { open: '09:00', close: '19:00', isClosed: false },
  tuesday: { open: '09:00', close: '19:00', isClosed: false },
  wednesday: { open: '09:00', close: '19:00', isClosed: false },
  thursday: { open: '09:00', close: '19:00', isClosed: false },
  friday: { open: '09:00', close: '13:00', isClosed: false },
  saturday: { open: '10:00', close: '17:00', isClosed: false },
  sunday: { open: '00:00', close: '00:00', isClosed: true },
}

// ─── Stations ────────────────────────────────────────

export const MOCK_STATIONS: Station[] = [
  {
    id: 'stn-001',
    slug: 'mall-road-ev-hub-lahore',
    name: 'Mall Road EV Hub',
    description:
      'Flagship 150 kW DC hub on The Mall, a short walk from Charing Cross. Covered bays, on-site attendant and a driver lounge with free Wi-Fi.',
    address: {
      street: 'The Mall, near Charing Cross',
      area: 'Mall Road',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    coordinates: { lat: 31.5589, lng: 74.3302 },
    connectors: [
      {
        id: 'stn-001-c1',
        type: 'CCS2',
        maxPowerKw: 150,
        ports: 2,
        availablePorts: 2,
        pricePerKwh: 78,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'BYD Seal', 'MG ZS EV', 'Hyundai Ioniq 5', 'KIA EV6'],
      },
      {
        id: 'stn-001-c2',
        type: 'CCS2',
        maxPowerKw: 60,
        ports: 1,
        availablePorts: 0,
        pricePerKwh: 68,
        isFree: false,
        status: 'in-use',
        compatibleVehicles: ['BYD Atto 3', 'MG ZS EV', 'Proton e.MAS 7'],
      },
      {
        id: 'stn-001-c3',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 1,
        pricePerKwh: 48,
        pricePerHour: 250,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4', 'Audi e-tron'],
      },
    ],
    amenities: [
      { type: 'restaurant', available: true, note: 'Two dine-in options within the plaza' },
      { type: 'cafe', available: true },
      { type: 'washroom', available: true },
      { type: 'wifi', available: true, note: 'Free, no password required' },
      { type: 'parking', available: true, note: 'Covered bays reserved for charging' },
      { type: 'prayer', available: true, note: 'Prayer room on the ground floor' },
      { type: 'shopping', available: true },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: [
      '/images/stations/mall-road-ev-hub-1.jpg',
      '/images/stations/mall-road-ev-hub-2.jpg',
      '/images/stations/mall-road-ev-hub-3.jpg',
    ],
    coverPhoto: '/images/stations/mall-road-ev-hub-1.jpg',
    rating: 4.8,
    reviewCount: 142,
    status: 'available',
    isVerified: true,
    network: 'Atlas Power',
    businessId: 'biz-001',
    createdAt: '2024-11-14T09:30:00+05:00',
    updatedAt: '2026-07-29T18:12:00+05:00',
    reviews: [
      {
        id: 'rev-001',
        userId: 'usr-101',
        userName: 'Ahmed Raza',
        userVehicle: 'BYD Atto 3',
        rating: 5,
        comment:
          'Pulled a genuine 142 kW on the main unit — 20 to 80 percent in just under half an hour. Attendant helped me line up the cable. Easily the best hub in Lahore right now.',
        date: '2026-07-24T14:20:00+05:00',
        helpfulCount: 31,
        isVerified: true,
      },
      {
        id: 'rev-002',
        userId: 'usr-102',
        userName: 'Fatima Khan',
        userVehicle: 'MG ZS EV',
        rating: 5,
        comment:
          'Charged here twice last week. Covered bays make a real difference in July heat, and the lounge Wi-Fi actually works. Card payment went through on the first try.',
        date: '2026-07-19T11:05:00+05:00',
        helpfulCount: 24,
        isVerified: true,
      },
      {
        id: 'rev-003',
        userId: 'usr-103',
        userName: 'Bilal Ahmad',
        userVehicle: 'Hyundai Ioniq 5',
        rating: 5,
        comment:
          'The 150 kW unit is properly liquid-cooled, so it holds power instead of tapering at 40 percent like most sites here. Ioniq 5 hit peak within a minute of plugging in.',
        date: '2026-07-11T20:40:00+05:00',
        helpfulCount: 18,
        isVerified: true,
      },
      {
        id: 'rev-004',
        userId: 'usr-104',
        userName: 'Ayesha Siddiqui',
        userVehicle: 'BYD Seal',
        rating: 4,
        comment:
          'No complaints about the charging itself. Only note is that the 60 kW unit is almost always occupied in the evenings, so aim for the main bay or come before 6pm.',
        date: '2026-07-02T17:55:00+05:00',
        helpfulCount: 12,
        isVerified: false,
      },
      {
        id: 'rev-005',
        userId: 'usr-105',
        userName: 'Usman Tariq',
        userVehicle: 'KIA EV6',
        rating: 5,
        comment:
          'Stopped here on the way back from Islamabad with 8 percent left. Plugged in, had dinner upstairs, came back to 82 percent. Tariff is fair for the speed you get.',
        date: '2026-06-27T21:30:00+05:00',
        helpfulCount: 9,
        isVerified: true,
      },
    ],
  },
  {
    id: 'stn-002',
    slug: 'f-10-charging-point-islamabad',
    name: 'F-10 Charging Point',
    description:
      'Dual-standard site in F-10 Markaz with one DC bay and two AC bays. Popular with commuters heading toward the Srinagar Highway.',
    address: {
      street: 'F-10 Markaz, Nazim-ud-din Road',
      area: 'F-10',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.6942, lng: 73.0122 },
    connectors: [
      {
        id: 'stn-002-c1',
        type: 'CCS2',
        maxPowerKw: 120,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 74,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'BYD Han', 'MG ZS EV', 'BMW iX', 'Proton e.MAS 7'],
      },
      {
        id: 'stn-002-c2',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 2,
        pricePerKwh: 46,
        pricePerHour: 220,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4', 'Mercedes EQS'],
      },
    ],
    amenities: [
      { type: 'cafe', available: true, note: 'Coffee shop directly opposite the bays' },
      { type: 'restaurant', available: true },
      { type: 'washroom', available: true },
      { type: 'parking', available: true },
      { type: 'shopping', available: true, note: 'Markaz shops within walking distance' },
      { type: 'prayer', available: true },
      { type: 'wifi', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: [
      '/images/stations/f-10-charging-point-1.jpg',
      '/images/stations/f-10-charging-point-2.jpg',
    ],
    coverPhoto: '/images/stations/f-10-charging-point-1.jpg',
    rating: 4.6,
    reviewCount: 88,
    status: 'available',
    isVerified: true,
    network: 'PSO EV Charge',
    createdAt: '2025-01-22T10:00:00+05:00',
    updatedAt: '2026-07-30T08:45:00+05:00',
    reviews: [
      {
        id: 'rev-006',
        userId: 'usr-106',
        userName: 'Zainab Malik',
        userVehicle: 'BYD Han',
        rating: 5,
        comment:
          'My default top-up spot in Islamabad. The DC unit is reliable and I have never had to queue on a weekday morning. Billing receipt comes by SMS straight away.',
        date: '2026-07-26T09:15:00+05:00',
        helpfulCount: 20,
        isVerified: true,
      },
      {
        id: 'rev-007',
        userId: 'usr-107',
        userName: 'Hassan Ali',
        userVehicle: 'MG ZS EV',
        rating: 5,
        comment:
          'Good location if you are heading out toward Srinagar Highway. Two AC bays mean you can almost always plug in even when the fast charger is busy.',
        date: '2026-07-15T16:30:00+05:00',
        helpfulCount: 14,
        isVerified: true,
      },
      {
        id: 'rev-008',
        userId: 'usr-108',
        userName: 'Sana Javed',
        userVehicle: 'BMW i4',
        rating: 4,
        comment:
          'Charging is solid but the bays are tight for a longer car and the cable barely reaches if you park nose-in. Reverse in and you will be fine.',
        date: '2026-07-04T13:10:00+05:00',
        helpfulCount: 11,
        isVerified: false,
      },
      {
        id: 'rev-009',
        userId: 'usr-109',
        userName: 'Imran Sheikh',
        userVehicle: 'Proton e.MAS 7',
        rating: 4,
        comment:
          'Reliable and clean, though it caps around 105 kW rather than the advertised 120. Still gets me to 80 percent in about 35 minutes, which is fine for a market stop.',
        date: '2026-06-18T19:20:00+05:00',
        helpfulCount: 7,
        isVerified: true,
      },
    ],
  },
  {
    id: 'stn-003',
    slug: 'clifton-fast-charge-karachi',
    name: 'Clifton Fast Charge',
    description:
      'Single 50 kW DC bay plus an AC backup in Clifton Block 4. One of the earliest public chargers in Karachi.',
    address: {
      street: 'Block 4, Khayaban-e-Roomi',
      area: 'Clifton',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75600',
    },
    coordinates: { lat: 24.8118, lng: 67.0301 },
    connectors: [
      {
        id: 'stn-003-c1',
        type: 'CCS2',
        maxPowerKw: 50,
        ports: 2,
        availablePorts: 1,
        pricePerKwh: 65,
        isFree: false,
        status: 'in-use',
        compatibleVehicles: ['BYD Atto 3', 'MG ZS EV', 'Changan Lumin'],
      },
      {
        id: 'stn-003-c2',
        type: 'Type2',
        maxPowerKw: 11,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 44,
        pricePerHour: 180,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4'],
      },
    ],
    amenities: [
      { type: 'restaurant', available: true, note: 'Several options along Khayaban-e-Roomi' },
      { type: 'cafe', available: true },
      { type: 'parking', available: true, note: 'Street parking only, can fill up after 7pm' },
      { type: 'washroom', available: true, note: 'Ask the attendant for access' },
      { type: 'shopping', available: true },
      { type: 'wifi', available: false },
      { type: 'prayer', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_MALL,
    photos: [
      '/images/stations/clifton-fast-charge-1.jpg',
      '/images/stations/clifton-fast-charge-2.jpg',
    ],
    coverPhoto: '/images/stations/clifton-fast-charge-1.jpg',
    rating: 4.2,
    reviewCount: 64,
    status: 'limited',
    isVerified: true,
    network: 'K-Electric ChargeUp',
    createdAt: '2024-08-03T12:00:00+05:00',
    updatedAt: '2026-07-30T07:20:00+05:00',
    reviews: [
      {
        id: 'rev-010',
        userId: 'usr-110',
        userName: 'Hina Butt',
        userVehicle: 'MG ZS EV',
        rating: 4,
        comment:
          'Does the job but 50 kW feels slow now that faster sites are opening. Expect 55 to 60 minutes for a proper top-up. Location and parking are convenient though.',
        date: '2026-07-21T18:00:00+05:00',
        helpfulCount: 16,
        isVerified: true,
      },
      {
        id: 'rev-011',
        userId: 'usr-111',
        userName: 'Kamran Aslam',
        userVehicle: 'BYD Atto 3',
        rating: 4,
        comment:
          'One of the two ports has been out of service for a couple of weeks, so plan for a wait in the evening. When it works, billing and speed are exactly as advertised.',
        date: '2026-07-09T20:15:00+05:00',
        helpfulCount: 22,
        isVerified: true,
      },
      {
        id: 'rev-012',
        userId: 'usr-112',
        userName: 'Maryam Farooq',
        userVehicle: 'Changan Lumin',
        rating: 5,
        comment:
          'Perfect for a small battery like the Lumin — 50 kW is more than my car can take anyway. Attendant is helpful and the site feels safe after dark.',
        date: '2026-06-30T15:45:00+05:00',
        helpfulCount: 8,
        isVerified: false,
      },
    ],
  },
  {
    id: 'stn-004',
    slug: 'gulberg-charging-station-lahore',
    name: 'Gulberg Charging Station',
    description:
      'Destination AC site in Gulberg III with three 22 kW bays. Best suited to a two to three hour stop rather than a quick top-up.',
    address: {
      street: 'Main Boulevard, Gulberg III',
      area: 'Gulberg',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54660',
    },
    coordinates: { lat: 31.5169, lng: 74.3484 },
    connectors: [
      {
        id: 'stn-004-c1',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 3,
        availablePorts: 2,
        pricePerKwh: 45,
        pricePerHour: 200,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG ZS EV', 'MG HS PHEV', 'BMW i4', 'Mercedes EQS'],
      },
      {
        id: 'stn-004-c2',
        type: 'Type1',
        maxPowerKw: 7.4,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 42,
        pricePerHour: 150,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['Nissan Leaf (imported)', 'Toyota Prius PHV (imported)'],
      },
    ],
    amenities: [
      { type: 'shopping', available: true, note: 'Main Boulevard retail on the same block' },
      { type: 'cafe', available: true },
      { type: 'restaurant', available: true },
      { type: 'wifi', available: true },
      { type: 'parking', available: true },
      { type: 'washroom', available: true },
      { type: 'prayer', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_MALL,
    photos: [
      '/images/stations/gulberg-charging-station-1.jpg',
      '/images/stations/gulberg-charging-station-2.jpg',
    ],
    coverPhoto: '/images/stations/gulberg-charging-station-1.jpg',
    rating: 4.4,
    reviewCount: 51,
    status: 'available',
    isVerified: false,
    network: 'EVolve Pakistan',
    businessId: 'biz-002',
    createdAt: '2025-03-17T11:30:00+05:00',
    updatedAt: '2026-07-28T16:00:00+05:00',
    reviews: [
      {
        id: 'rev-013',
        userId: 'usr-113',
        userName: 'Saad Rehman',
        userVehicle: 'BYD Atto 3',
        rating: 5,
        comment:
          'Exactly what a destination charger should be. Leave the car on 22 kW, go do your shopping, come back with 40 percent more. Cheapest per-kWh rate I have found in Lahore.',
        date: '2026-07-23T15:00:00+05:00',
        helpfulCount: 13,
        isVerified: true,
      },
      {
        id: 'rev-014',
        userId: 'usr-114',
        userName: 'Rabia Anwar',
        userVehicle: 'MG HS PHEV',
        rating: 4,
        comment:
          'Great for a plug-in hybrid — full charge in about two hours while I was at lunch nearby. Three bays means I have never seen it completely full.',
        date: '2026-07-06T13:25:00+05:00',
        helpfulCount: 9,
        isVerified: true,
      },
      {
        id: 'rev-015',
        userId: 'usr-115',
        userName: 'Tahir Mehmood',
        userVehicle: 'MG ZS EV',
        rating: 4,
        comment:
          'Do not come here if you are in a hurry — it is AC only, so a 20 to 80 percent run takes the better part of three hours. Priced accordingly and well maintained.',
        date: '2026-06-14T12:40:00+05:00',
        helpfulCount: 17,
        isVerified: false,
      },
    ],
  },
  {
    id: 'stn-005',
    slug: 'blue-area-ev-station-islamabad',
    name: 'Blue Area EV Station',
    description:
      'Two-bay 150 kW site on Jinnah Avenue. Currently offline for a transformer upgrade — the operator expects to restore service in August 2026.',
    address: {
      street: 'Jinnah Avenue, Blue Area',
      area: 'Blue Area',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.7089, lng: 73.0641 },
    connectors: [
      {
        id: 'stn-005-c1',
        type: 'CCS2',
        maxPowerKw: 150,
        ports: 2,
        availablePorts: 0,
        pricePerKwh: 80,
        isFree: false,
        status: 'offline',
        compatibleVehicles: ['BYD Seal', 'BYD Han', 'BMW iX', 'Mercedes EQS', 'KIA EV6'],
      },
      {
        id: 'stn-005-c2',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 0,
        pricePerKwh: 50,
        pricePerHour: 240,
        isFree: false,
        status: 'offline',
        compatibleVehicles: ['BYD Atto 3', 'BMW i4', 'Mercedes EQS'],
      },
    ],
    amenities: [
      { type: 'restaurant', available: true },
      { type: 'cafe', available: true },
      { type: 'parking', available: true, note: 'Paid underground parking' },
      { type: 'prayer', available: true },
      { type: 'washroom', available: true },
      { type: 'shopping', available: false },
      { type: 'wifi', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: ['/images/stations/blue-area-ev-station-1.jpg'],
    coverPhoto: '/images/stations/blue-area-ev-station-1.jpg',
    rating: 4.0,
    reviewCount: 37,
    status: 'offline',
    isVerified: true,
    network: 'Renergent',
    createdAt: '2025-05-09T14:15:00+05:00',
    updatedAt: '2026-07-27T10:05:00+05:00',
    reviews: [
      {
        id: 'rev-016',
        userId: 'usr-116',
        userName: 'Adeel Hussain',
        userVehicle: 'BYD Seal',
        rating: 4,
        comment:
          'Was a genuinely fast site before it went down — 130 kW sustained on my Seal. Currently offline for a transformer upgrade, so check the app before driving over.',
        date: '2026-07-18T17:10:00+05:00',
        helpfulCount: 28,
        isVerified: true,
      },
      {
        id: 'rev-017',
        userId: 'usr-117',
        userName: 'Sadia Iqbal',
        userVehicle: 'Mercedes EQS',
        rating: 4,
        comment:
          'Turned up on a Sunday with both bays dead and no notice on site. Staff at the plaza confirmed it has been down for a few weeks. Please update the status board.',
        date: '2026-07-12T11:50:00+05:00',
        helpfulCount: 33,
        isVerified: true,
      },
      {
        id: 'rev-018',
        userId: 'usr-118',
        userName: 'Farhan Qureshi',
        userVehicle: 'BMW iX',
        rating: 4,
        comment:
          'Excellent location right on Jinnah Avenue and the hardware is good quality. Docking a star only for the current outage — worth revisiting once it is back.',
        date: '2026-06-25T09:35:00+05:00',
        helpfulCount: 15,
        isVerified: false,
      },
    ],
  },
  {
    id: 'stn-006',
    slug: 'dha-charging-hub-karachi',
    name: 'DHA Charging Hub',
    description:
      'The only public CHAdeMO in Karachi alongside a 120 kW CCS2 bay, making it the go-to site for imported Nissan Leafs as well as newer CCS2 cars.',
    address: {
      street: 'Khayaban-e-Ittehad, Phase 6',
      area: 'DHA Phase 6',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75500',
    },
    coordinates: { lat: 24.7983, lng: 67.0531 },
    connectors: [
      {
        id: 'stn-006-c1',
        type: 'CCS2',
        maxPowerKw: 120,
        ports: 2,
        availablePorts: 2,
        pricePerKwh: 76,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'BYD Seal', 'MG ZS EV', 'Hyundai Ioniq 5', 'BMW iX'],
      },
      {
        id: 'stn-006-c2',
        type: 'CHAdeMO',
        maxPowerKw: 50,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 70,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['Nissan Leaf', 'Nissan Leaf e+', 'Mitsubishi Outlander PHEV'],
      },
      {
        id: 'stn-006-c3',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 1,
        pricePerKwh: 47,
        pricePerHour: 210,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4'],
      },
    ],
    amenities: [
      { type: 'cafe', available: true, note: 'Two cafés in the same commercial strip' },
      { type: 'restaurant', available: true },
      { type: 'washroom', available: true },
      { type: 'wifi', available: true },
      { type: 'parking', available: true, note: 'Dedicated EV bays, enforced by security' },
      { type: 'prayer', available: true },
      { type: 'shopping', available: true },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: [
      '/images/stations/dha-charging-hub-1.jpg',
      '/images/stations/dha-charging-hub-2.jpg',
      '/images/stations/dha-charging-hub-3.jpg',
    ],
    coverPhoto: '/images/stations/dha-charging-hub-1.jpg',
    rating: 4.9,
    reviewCount: 176,
    status: 'available',
    isVerified: true,
    network: 'Shell Recharge',
    businessId: 'biz-003',
    createdAt: '2024-06-28T08:00:00+05:00',
    updatedAt: '2026-07-30T06:30:00+05:00',
    reviews: [
      {
        id: 'rev-019',
        userId: 'usr-119',
        userName: 'Omar Faridi',
        userVehicle: 'Nissan Leaf e+',
        rating: 5,
        comment:
          'The only reliable public CHAdeMO in the city. As a Leaf owner this station is the reason long trips inside Karachi are practical at all. Never found it broken.',
        date: '2026-07-28T10:30:00+05:00',
        helpfulCount: 41,
        isVerified: true,
      },
      {
        id: 'rev-020',
        userId: 'usr-120',
        userName: 'Nida Aslam',
        userVehicle: 'BYD Seal',
        rating: 5,
        comment:
          'Six ports across three standards means zero waiting, even at peak. Dedicated bays are actually enforced by security so you never find a petrol car parked in one.',
        date: '2026-07-20T19:45:00+05:00',
        helpfulCount: 27,
        isVerified: true,
      },
      {
        id: 'rev-021',
        userId: 'usr-121',
        userName: 'Junaid Sattar',
        userVehicle: 'Hyundai Ioniq 5',
        rating: 5,
        comment:
          'Consistent 115 kW on the CCS2 side and the site is spotless. Cafés next door make the 25 minute stop painless. Best charging experience in Karachi by a wide margin.',
        date: '2026-07-13T14:15:00+05:00',
        helpfulCount: 19,
        isVerified: true,
      },
      {
        id: 'rev-022',
        userId: 'usr-122',
        userName: 'Sarah Ashraf',
        userVehicle: 'MG ZS EV',
        rating: 5,
        comment:
          'Well lit, staffed around the clock and the app shows live port availability that actually matches reality. Slightly pricier per unit but worth it for the reliability.',
        date: '2026-07-01T21:00:00+05:00',
        helpfulCount: 14,
        isVerified: false,
      },
      {
        id: 'rev-023',
        userId: 'usr-123',
        userName: 'Waqas Ahmed',
        userVehicle: 'BYD Atto 3',
        rating: 4,
        comment:
          'Hard to fault the hardware or the service. Only reason for four stars is the tariff — about 10 rupees a unit more than Clifton, which adds up on a full charge.',
        date: '2026-06-22T16:20:00+05:00',
        helpfulCount: 11,
        isVerified: true,
      },
    ],
  },
]

// ─── EV Models ───────────────────────────────────────

export const MOCK_EV_MODELS: EVModel[] = [
  {
    id: 'ev-001',
    make: 'BYD',
    model: 'Atto 3',
    year: 2024,
    rangeKm: 480,
    batteryCapacityKwh: 60.5,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 88,
  },
  {
    id: 'ev-002',
    make: 'BYD',
    model: 'Seal',
    year: 2024,
    rangeKm: 580,
    batteryCapacityKwh: 82.5,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 150,
  },
  {
    id: 'ev-003',
    make: 'BYD',
    model: 'Han',
    year: 2023,
    rangeKm: 521,
    batteryCapacityKwh: 85.4,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 120,
  },
  {
    id: 'ev-004',
    make: 'MG',
    model: 'ZS EV',
    year: 2024,
    rangeKm: 440,
    batteryCapacityKwh: 50.3,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 76,
  },
  {
    id: 'ev-005',
    make: 'Changan',
    model: 'Lumin',
    year: 2024,
    rangeKm: 301,
    batteryCapacityKwh: 32.8,
    connectorTypes: ['GBT'],
    chargingSpeedKw: 40,
  },
  {
    id: 'ev-006',
    make: 'Proton',
    model: 'e.MAS 7',
    year: 2024,
    rangeKm: 430,
    batteryCapacityKwh: 60.2,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 80,
  },
  {
    id: 'ev-007',
    make: 'BMW',
    model: 'i4',
    year: 2023,
    rangeKm: 590,
    batteryCapacityKwh: 83.9,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 205,
  },
  {
    id: 'ev-008',
    make: 'BMW',
    model: 'iX',
    year: 2023,
    rangeKm: 630,
    batteryCapacityKwh: 111.5,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 195,
  },
  {
    id: 'ev-009',
    make: 'Mercedes',
    model: 'EQS',
    year: 2023,
    rangeKm: 770,
    batteryCapacityKwh: 107.8,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 200,
  },
  {
    id: 'ev-010',
    make: 'Nissan',
    model: 'Leaf e+',
    year: 2022,
    rangeKm: 385,
    batteryCapacityKwh: 62,
    connectorTypes: ['CHAdeMO', 'Type1'],
    chargingSpeedKw: 100,
  },
]

// ─── EV Services ─────────────────────────────────────

export const MOCK_SERVICES: EVService[] = [
  {
    id: 'svc-001',
    slug: 'byd-lahore-flagship-dealership',
    name: 'BYD Lahore Flagship',
    category: 'dealership',
    description:
      'Authorised BYD dealership on Main Boulevard covering the Atto 3, Seal and Han. Test drives available on booking, with an on-site delivery bay and finance desk.',
    address: {
      street: 'Main Boulevard, Gulberg II',
      area: 'Gulberg',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54660',
    },
    coordinates: { lat: 31.5102, lng: 74.3441 },
    phone: '+92 42 3577 4100',
    email: 'lahore@bydpakistan.example',
    website: 'https://byd.example.pk/lahore',
    photos: [
      '/images/services/byd-lahore-1.jpg',
      '/images/services/byd-lahore-2.jpg',
    ],
    coverPhoto: '/images/services/byd-lahore-1.jpg',
    rating: 4.7,
    reviewCount: 96,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2024-09-12T10:00:00+05:00',
  },
  {
    id: 'svc-002',
    slug: 'voltway-home-charger-installation-islamabad',
    name: 'VoltWay Home Charger Installation',
    category: 'home-charger-installer',
    description:
      'Certified installers for 7.4 kW and 22 kW home wallboxes across Islamabad and Rawalpindi. Includes load assessment, dedicated breaker, earthing check and WAPDA compliance paperwork.',
    address: {
      street: 'Office 12, Kohistan Plaza, I-8 Markaz',
      area: 'I-8',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.6706, lng: 73.0752 },
    phone: '+92 51 2856 730',
    email: 'install@voltway.example',
    website: 'https://voltway.example.pk',
    photos: ['/images/services/voltway-1.jpg'],
    coverPhoto: '/images/services/voltway-1.jpg',
    rating: 4.8,
    reviewCount: 54,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2025-02-05T09:30:00+05:00',
  },
  {
    id: 'svc-003',
    slug: 'karachi-ev-care-service-centre',
    name: 'Karachi EV Care',
    category: 'service-center',
    description:
      'High-voltage certified workshop in SITE handling battery diagnostics, thermal system service and warranty work for BYD, MG and imported Japanese EVs.',
    address: {
      street: 'Plot 44-C, SITE Area',
      area: 'SITE',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75700',
    },
    coordinates: { lat: 24.8918, lng: 66.9987 },
    phone: '+92 21 3255 8890',
    email: 'service@karachievcare.example',
    photos: [
      '/images/services/karachi-ev-care-1.jpg',
      '/images/services/karachi-ev-care-2.jpg',
    ],
    coverPhoto: '/images/services/karachi-ev-care-1.jpg',
    rating: 4.5,
    reviewCount: 71,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2024-12-01T08:45:00+05:00',
  },
]

// ─── Community Posts ─────────────────────────────────

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 'post-001',
    slug: 'lahore-to-islamabad-in-a-byd-atto-3-one-stop',
    userId: 'usr-101',
    userName: 'Ahmed Raza',
    userVehicle: 'BYD Atto 3',
    title: 'Lahore to Islamabad in an Atto 3 — one stop, 4h 55m door to door',
    content:
      'Did the M-2 run on Saturday and it is now genuinely a one-stop trip. Left Lahore at 92 percent, sat at 110 km/h with the AC on, and rolled into the Bhera service area with 34 percent left after 265 km.\n\nCharged for 28 minutes to 78 percent, which was more than enough for the remaining 110 km plus city driving. Total door to door was 4 hours 55 minutes including the stop, so maybe 20 minutes more than I would have taken in a petrol car.\n\nTwo things worth knowing. Real-world consumption at motorway speed was 17.8 kWh/100km, noticeably worse than the 15.2 I see around town, so do not plan on the NEDC number. And the fast charger at Bhera tapers hard past 80 percent, so it is quicker to leave at 78 and stop again than to wait it out.',
    category: 'trip-report',
    photos: [
      '/images/community/m2-trip-1.jpg',
      '/images/community/m2-trip-2.jpg',
    ],
    likeCount: 214,
    commentCount: 3,
    createdAt: '2026-07-26T20:15:00+05:00',
    updatedAt: '2026-07-26T20:15:00+05:00',
    comments: [
      {
        id: 'cmt-001',
        postId: 'post-001',
        userId: 'usr-107',
        userName: 'Hassan Ali',
        content:
          'This matches my experience almost exactly in a ZS EV, except I need two stops because of the smaller battery. The taper point on the Bhera unit is the key detail — took me three trips to work that out.',
        likeCount: 27,
        createdAt: '2026-07-26T21:40:00+05:00',
      },
      {
        id: 'cmt-002',
        postId: 'post-001',
        userId: 'usr-106',
        userName: 'Zainab Malik',
        content:
          'Did you try 100 km/h instead of 110? On my Han the drop from 120 to 100 is worth nearly 60 km of range, which is often cheaper than the extra charging stop.',
        likeCount: 15,
        createdAt: '2026-07-27T09:05:00+05:00',
      },
      {
        id: 'cmt-003',
        postId: 'post-001',
        userId: 'usr-113',
        userName: 'Saad Rehman',
        content:
          'Useful writeup. Worth adding that the Bhera site only has two working ports, so on Eid weekends there was a 40 minute queue. Mall Road hub before you leave Lahore is a safer bet.',
        likeCount: 22,
        createdAt: '2026-07-27T13:30:00+05:00',
      },
    ],
  },
  {
    id: 'post-002',
    slug: 'six-months-with-an-mg-zs-ev-running-costs',
    userId: 'usr-102',
    userName: 'Fatima Khan',
    userVehicle: 'MG ZS EV',
    title: 'Six months and 11,000 km with a ZS EV — actual running costs',
    content:
      'I kept every charging receipt since January, so here are real numbers rather than estimates.\n\nOf 11,000 km, roughly 70 percent was charged at home on a 7.4 kW wallbox and 30 percent on public DC. Home charging worked out to about 42 rupees per unit on the protected slab, public DC averaged 71. Blended cost came to 3.4 rupees per kilometre.\n\nMy old 1.6 Corolla was doing about 12 km per litre, so call it 22 rupees per kilometre. Over 11,000 km that is a saving of roughly 205,000 rupees in fuel alone.\n\nThe honest caveats: I have had one unplanned service visit for a coolant pump, load-shedding means I sometimes cannot charge overnight, and resale value on EVs here is still an unknown. But on running cost the case is not close.',
    category: 'vehicle-review',
    photos: ['/images/community/zs-ev-costs-1.jpg'],
    likeCount: 389,
    commentCount: 2,
    createdAt: '2026-07-18T11:20:00+05:00',
    updatedAt: '2026-07-19T08:05:00+05:00',
    comments: [
      {
        id: 'cmt-004',
        postId: 'post-002',
        userId: 'usr-115',
        userName: 'Tahir Mehmood',
        content:
          'Thank you for using real receipts instead of the usual per-100km guesswork. The 3.4 rupees per km figure lines up with what I calculated over a shorter period.',
        likeCount: 41,
        createdAt: '2026-07-18T14:50:00+05:00',
      },
      {
        id: 'cmt-005',
        postId: 'post-002',
        userId: 'usr-111',
        userName: 'Kamran Aslam',
        content:
          'Worth noting the protected slab only applies under 200 units a month. Once you cross that, home charging jumps closer to 60 a unit and the maths changes for anyone driving more than you.',
        likeCount: 36,
        createdAt: '2026-07-19T07:15:00+05:00',
      },
    ],
  },
  {
    id: 'post-003',
    slug: 'which-connector-should-i-look-for-buying-first-ev',
    userId: 'usr-110',
    userName: 'Hina Butt',
    userVehicle: 'MG ZS EV',
    title: 'Buying your first EV in Pakistan? Check the connector before anything else',
    content:
      'Seeing a lot of posts from people about to buy an imported EV without checking what they can actually plug into, so here is the short version.\n\nCCS2 is the safe choice. Almost every new public DC charger going up in Lahore, Islamabad and Karachi is CCS2, and every locally sold BYD, MG and Proton uses it.\n\nCHAdeMO is the risk. It is fine if you are buying an imported Leaf and you live near DHA in Karachi, but there is essentially one reliable public CHAdeMO in the entire city. Anywhere else and you are on home AC charging only.\n\nGB/T shows up on some directly imported Chinese cars. Public GB/T is close to non-existent here, so treat those as home-charge-only vehicles.\n\nType 2 is the AC standard and every modern EV has it. Slow, but universal — useful as a fallback everywhere.\n\nBefore you commit to a car, open the map, filter by its connector, and look at what is within 20 km of your home and office. If the answer is one station, think carefully.',
    category: 'buying-advice',
    likeCount: 502,
    commentCount: 2,
    createdAt: '2026-07-08T16:45:00+05:00',
    updatedAt: '2026-07-08T16:45:00+05:00',
    comments: [
      {
        id: 'cmt-006',
        postId: 'post-003',
        userId: 'usr-119',
        userName: 'Omar Faridi',
        content:
          'Leaf owner here and this is fair. I love the car and DHA Charging Hub has never let me down, but if I lived in Lahore I would not have bought it. Buy the connector, not just the car.',
        likeCount: 88,
        createdAt: '2026-07-08T19:30:00+05:00',
      },
      {
        id: 'cmt-007',
        postId: 'post-003',
        userId: 'usr-112',
        userName: 'Maryam Farooq',
        content:
          'Would add one thing for GB/T owners like me: a decent portable AC charger is not optional, it is part of the purchase price. Budget for it up front.',
        likeCount: 45,
        createdAt: '2026-07-09T10:10:00+05:00',
      },
    ],
  },
]

// ─── Platform Stats ──────────────────────────────────

export const MOCK_PLATFORM_STATS: PlatformStats = {
  totalStations: 250,
  totalCities: 18,
  totalUsers: 5000,
  totalReviews: 1200,
}
