// src/lib/mock-data.ts
// ═══════════════════════════════════════════════════
// PLUG.PK — MOCK DATA
// Development fixtures. Replace with API calls in a later phase.
// ═══════════════════════════════════════════════════

import type {
  CommunityPost,
  EVModel,
  EVService,
  OperatingHours,
  PlatformStats,
  Station,
  Business,
  User,
  Review,
  ActivityItem,
  EVClub,
} from './types'

// ─── Shared Operating-Hour Presets ───────────────────

const HOURS_24_7: OperatingHours = {
  is24Hours: true,
  monday: { open: '00:00', close: '23:59', isClosed: false },
  tuesday: { open: '00:00', close: '23:59', isClosed: false },
  wednesday: { open: '00:00', close: '23:59', isClosed: false },
  thursday: { open: '00:00', close: '23:59', isClosed: false },
  friday: { open: '00:00', close: '23:59', isClosed: false },
  saturday: { open: '00:00', close: '23:59', isClosed: false },
  sunday: { open: '00:00', close: '23:59', isClosed: false },
}

const HOURS_MALL: OperatingHours = {
  is24Hours: false,
  monday: { open: '10:00', close: '23:00', isClosed: false },
  tuesday: { open: '10:00', close: '23:00', isClosed: false },
  wednesday: { open: '10:00', close: '23:00', isClosed: false },
  thursday: { open: '10:00', close: '23:00', isClosed: false },
  friday: { open: '14:00', close: '23:00', isClosed: false },
  saturday: { open: '10:00', close: '00:00', isClosed: false },
  sunday: { open: '10:00', close: '00:00', isClosed: false },
}

const HOURS_BUSINESS: OperatingHours = {
  is24Hours: false,
  monday: { open: '09:00', close: '19:00', isClosed: false },
  tuesday: { open: '09:00', close: '19:00', isClosed: false },
  wednesday: { open: '09:00', close: '19:00', isClosed: false },
  thursday: { open: '09:00', close: '19:00', isClosed: false },
  friday: { open: '09:00', close: '13:00', isClosed: false },
  saturday: { open: '10:00', close: '17:00', isClosed: false },
  sunday: { open: '00:00', close: '00:00', isClosed: true },
}

// ─── Stations ────────────────────────────────────────

export const MOCK_STATIONS: Station[] = [
  {
    id: 'stn-001',
    slug: 'mall-road-ev-hub-lahore',
    name: 'Mall Road EV Hub',
    description:
      'Flagship 150 kW DC hub on The Mall, a short walk from Charing Cross. Covered bays, on-site attendant and a driver lounge with free Wi-Fi.',
    address: {
      street: 'The Mall, near Charing Cross',
      area: 'Mall Road',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54000',
    },
    coordinates: { lat: 31.5589, lng: 74.3302 },
    connectors: [
      {
        id: 'stn-001-c1',
        type: 'CCS2',
        maxPowerKw: 150,
        ports: 2,
        availablePorts: 2,
        pricePerKwh: 78,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'BYD Seal', 'MG ZS EV', 'Hyundai Ioniq 5', 'KIA EV6'],
      },
      {
        id: 'stn-001-c2',
        type: 'CCS2',
        maxPowerKw: 60,
        ports: 1,
        availablePorts: 0,
        pricePerKwh: 68,
        isFree: false,
        status: 'in-use',
        compatibleVehicles: ['BYD Atto 3', 'MG ZS EV', 'Proton e.MAS 7'],
      },
      {
        id: 'stn-001-c3',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 1,
        pricePerKwh: 48,
        pricePerHour: 250,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4', 'Audi e-tron'],
      },
    ],
    amenities: [
      { type: 'restaurant', available: true, note: 'Two dine-in options within the plaza' },
      { type: 'cafe', available: true },
      { type: 'washroom', available: true },
      { type: 'wifi', available: true, note: 'Free, no password required' },
      { type: 'parking', available: true, note: 'Covered bays reserved for charging' },
      { type: 'prayer', available: true, note: 'Prayer room on the ground floor' },
      { type: 'shopping', available: true },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: [
      '/images/stations/mall-road-ev-hub-1.jpg',
      '/images/stations/mall-road-ev-hub-2.jpg',
      '/images/stations/mall-road-ev-hub-3.jpg',
    ],
    coverPhoto: '/images/stations/mall-road-ev-hub-1.jpg',
    rating: 4.8,
    reviewCount: 142,
    status: 'available',
    isVerified: true,
    network: 'Atlas Power',
    phone: '+92 42 3628 4410',
    website: 'https://atlaspower.example.pk/mall-road',
    businessId: 'biz-001',
    createdAt: '2024-11-14T09:30:00+05:00',
    updatedAt: '2026-07-29T18:12:00+05:00',
    reviews: [
      {
        id: 'rev-001',
        userId: 'usr-101',
        userName: 'Ahmed Raza',
        userVehicle: 'BYD Atto 3',
        rating: 5,
        comment:
          'Pulled a genuine 142 kW on the main unit — 20 to 80 percent in just under half an hour. Attendant helped me line up the cable. Easily the best hub in Lahore right now.',
        date: '2026-07-24T14:20:00+05:00',
        helpfulCount: 31,
        isVerified: true,
      },
      {
        id: 'rev-002',
        userId: 'usr-102',
        userName: 'Fatima Khan',
        userVehicle: 'MG ZS EV',
        rating: 5,
        comment:
          'Charged here twice last week. Covered bays make a real difference in July heat, and the lounge Wi-Fi actually works. Card payment went through on the first try.',
        date: '2026-07-19T11:05:00+05:00',
        helpfulCount: 24,
        isVerified: true,
      },
      {
        id: 'rev-003',
        userId: 'usr-103',
        userName: 'Bilal Ahmad',
        userVehicle: 'Hyundai Ioniq 5',
        rating: 5,
        comment:
          'The 150 kW unit is properly liquid-cooled, so it holds power instead of tapering at 40 percent like most sites here. Ioniq 5 hit peak within a minute of plugging in.',
        date: '2026-07-11T20:40:00+05:00',
        helpfulCount: 18,
        isVerified: true,
      },
      {
        id: 'rev-004',
        userId: 'usr-104',
        userName: 'Ayesha Siddiqui',
        userVehicle: 'BYD Seal',
        rating: 4,
        comment:
          'No complaints about the charging itself. Only note is that the 60 kW unit is almost always occupied in the evenings, so aim for the main bay or come before 6pm.',
        date: '2026-07-02T17:55:00+05:00',
        helpfulCount: 12,
        isVerified: false,
      },
      {
        id: 'rev-005',
        userId: 'usr-105',
        userName: 'Usman Tariq',
        userVehicle: 'KIA EV6',
        rating: 5,
        comment:
          'Stopped here on the way back from Islamabad with 8 percent left. Plugged in, had dinner upstairs, came back to 82 percent. Tariff is fair for the speed you get.',
        date: '2026-06-27T21:30:00+05:00',
        helpfulCount: 9,
        isVerified: true,
      },
    ],
  },
  {
    id: 'stn-002',
    slug: 'f-10-charging-point-islamabad',
    name: 'F-10 Charging Point',
    description:
      'Dual-standard site in F-10 Markaz with one DC bay and two AC bays. Popular with commuters heading toward the Srinagar Highway.',
    address: {
      street: 'F-10 Markaz, Nazim-ud-din Road',
      area: 'F-10',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.6942, lng: 73.0122 },
    connectors: [
      {
        id: 'stn-002-c1',
        type: 'CCS2',
        maxPowerKw: 120,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 74,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'BYD Han', 'MG ZS EV', 'BMW iX', 'Proton e.MAS 7'],
      },
      {
        id: 'stn-002-c2',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 2,
        pricePerKwh: 46,
        pricePerHour: 220,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4', 'Mercedes EQS'],
      },
    ],
    amenities: [
      { type: 'cafe', available: true, note: 'Coffee shop directly opposite the bays' },
      { type: 'restaurant', available: true },
      { type: 'washroom', available: true },
      { type: 'parking', available: true },
      { type: 'shopping', available: true, note: 'Markaz shops within walking distance' },
      { type: 'prayer', available: true },
      { type: 'wifi', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: [
      '/images/stations/f-10-charging-point-1.jpg',
      '/images/stations/f-10-charging-point-2.jpg',
    ],
    coverPhoto: '/images/stations/f-10-charging-point-1.jpg',
    rating: 4.6,
    reviewCount: 88,
    status: 'available',
    isVerified: true,
    network: 'PSO EV Charge',
    createdAt: '2025-01-22T10:00:00+05:00',
    updatedAt: '2026-07-30T08:45:00+05:00',
    reviews: [
      {
        id: 'rev-006',
        userId: 'usr-106',
        userName: 'Zainab Malik',
        userVehicle: 'BYD Han',
        rating: 5,
        comment:
          'My default top-up spot in Islamabad. The DC unit is reliable and I have never had to queue on a weekday morning. Billing receipt comes by SMS straight away.',
        date: '2026-07-26T09:15:00+05:00',
        helpfulCount: 20,
        isVerified: true,
      },
      {
        id: 'rev-007',
        userId: 'usr-107',
        userName: 'Hassan Ali',
        userVehicle: 'MG ZS EV',
        rating: 5,
        comment:
          'Good location if you are heading out toward Srinagar Highway. Two AC bays mean you can almost always plug in even when the fast charger is busy.',
        date: '2026-07-15T16:30:00+05:00',
        helpfulCount: 14,
        isVerified: true,
      },
      {
        id: 'rev-008',
        userId: 'usr-108',
        userName: 'Sana Javed',
        userVehicle: 'BMW i4',
        rating: 4,
        comment:
          'Charging is solid but the bays are tight for a longer car and the cable barely reaches if you park nose-in. Reverse in and you will be fine.',
        date: '2026-07-04T13:10:00+05:00',
        helpfulCount: 11,
        isVerified: false,
      },
      {
        id: 'rev-009',
        userId: 'usr-109',
        userName: 'Imran Sheikh',
        userVehicle: 'Proton e.MAS 7',
        rating: 4,
        comment:
          'Reliable and clean, though it caps around 105 kW rather than the advertised 120. Still gets me to 80 percent in about 35 minutes, which is fine for a market stop.',
        date: '2026-06-18T19:20:00+05:00',
        helpfulCount: 7,
        isVerified: true,
      },
    ],
  },
  {
    id: 'stn-003',
    slug: 'clifton-fast-charge-karachi',
    name: 'Clifton Fast Charge',
    description:
      'Single 50 kW DC bay plus an AC backup in Clifton Block 4. One of the earliest public chargers in Karachi.',
    address: {
      street: 'Block 4, Khayaban-e-Roomi',
      area: 'Clifton',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75600',
    },
    coordinates: { lat: 24.8118, lng: 67.0301 },
    connectors: [
      {
        id: 'stn-003-c1',
        type: 'CCS2',
        maxPowerKw: 50,
        ports: 2,
        availablePorts: 1,
        pricePerKwh: 65,
        isFree: false,
        status: 'in-use',
        compatibleVehicles: ['BYD Atto 3', 'MG ZS EV', 'Changan Lumin'],
      },
      {
        id: 'stn-003-c2',
        type: 'Type2',
        maxPowerKw: 11,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 44,
        pricePerHour: 180,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4'],
      },
    ],
    amenities: [
      { type: 'restaurant', available: true, note: 'Several options along Khayaban-e-Roomi' },
      { type: 'cafe', available: true },
      { type: 'parking', available: true, note: 'Street parking only, can fill up after 7pm' },
      { type: 'washroom', available: true, note: 'Ask the attendant for access' },
      { type: 'shopping', available: true },
      { type: 'wifi', available: false },
      { type: 'prayer', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_MALL,
    photos: [
      '/images/stations/clifton-fast-charge-1.jpg',
      '/images/stations/clifton-fast-charge-2.jpg',
    ],
    coverPhoto: '/images/stations/clifton-fast-charge-1.jpg',
    rating: 4.2,
    reviewCount: 64,
    status: 'limited',
    isVerified: true,
    network: 'K-Electric ChargeUp',
    createdAt: '2024-08-03T12:00:00+05:00',
    updatedAt: '2026-07-30T07:20:00+05:00',
    reviews: [
      {
        id: 'rev-010',
        userId: 'usr-110',
        userName: 'Hina Butt',
        userVehicle: 'MG ZS EV',
        rating: 4,
        comment:
          'Does the job but 50 kW feels slow now that faster sites are opening. Expect 55 to 60 minutes for a proper top-up. Location and parking are convenient though.',
        date: '2026-07-21T18:00:00+05:00',
        helpfulCount: 16,
        isVerified: true,
      },
      {
        id: 'rev-011',
        userId: 'usr-111',
        userName: 'Kamran Aslam',
        userVehicle: 'BYD Atto 3',
        rating: 4,
        comment:
          'One of the two ports has been out of service for a couple of weeks, so plan for a wait in the evening. When it works, billing and speed are exactly as advertised.',
        date: '2026-07-09T20:15:00+05:00',
        helpfulCount: 22,
        isVerified: true,
      },
      {
        id: 'rev-012',
        userId: 'usr-112',
        userName: 'Maryam Farooq',
        userVehicle: 'Changan Lumin',
        rating: 5,
        comment:
          'Perfect for a small battery like the Lumin — 50 kW is more than my car can take anyway. Attendant is helpful and the site feels safe after dark.',
        date: '2026-06-30T15:45:00+05:00',
        helpfulCount: 8,
        isVerified: false,
      },
    ],
  },
  {
    id: 'stn-004',
    slug: 'gulberg-charging-station-lahore',
    name: 'Gulberg Charging Station',
    description:
      'Destination AC site in Gulberg III with three 22 kW bays. Best suited to a two to three hour stop rather than a quick top-up.',
    address: {
      street: 'Main Boulevard, Gulberg III',
      area: 'Gulberg',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54660',
    },
    coordinates: { lat: 31.5169, lng: 74.3484 },
    connectors: [
      {
        id: 'stn-004-c1',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 3,
        availablePorts: 2,
        pricePerKwh: 45,
        pricePerHour: 200,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG ZS EV', 'MG HS PHEV', 'BMW i4', 'Mercedes EQS'],
      },
      {
        id: 'stn-004-c2',
        type: 'Type1',
        maxPowerKw: 7.4,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 42,
        pricePerHour: 150,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['Nissan Leaf (imported)', 'Toyota Prius PHV (imported)'],
      },
    ],
    amenities: [
      { type: 'shopping', available: true, note: 'Main Boulevard retail on the same block' },
      { type: 'cafe', available: true },
      { type: 'restaurant', available: true },
      { type: 'wifi', available: true },
      { type: 'parking', available: true },
      { type: 'washroom', available: true },
      { type: 'prayer', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_MALL,
    photos: [
      '/images/stations/gulberg-charging-station-1.jpg',
      '/images/stations/gulberg-charging-station-2.jpg',
    ],
    coverPhoto: '/images/stations/gulberg-charging-station-1.jpg',
    rating: 4.4,
    reviewCount: 51,
    status: 'available',
    isVerified: false,
    network: 'EVolve Pakistan',
    businessId: 'biz-002',
    createdAt: '2025-03-17T11:30:00+05:00',
    updatedAt: '2026-07-28T16:00:00+05:00',
    reviews: [
      {
        id: 'rev-013',
        userId: 'usr-113',
        userName: 'Saad Rehman',
        userVehicle: 'BYD Atto 3',
        rating: 5,
        comment:
          'Exactly what a destination charger should be. Leave the car on 22 kW, go do your shopping, come back with 40 percent more. Cheapest per-kWh rate I have found in Lahore.',
        date: '2026-07-23T15:00:00+05:00',
        helpfulCount: 13,
        isVerified: true,
      },
      {
        id: 'rev-014',
        userId: 'usr-114',
        userName: 'Rabia Anwar',
        userVehicle: 'MG HS PHEV',
        rating: 4,
        comment:
          'Great for a plug-in hybrid — full charge in about two hours while I was at lunch nearby. Three bays means I have never seen it completely full.',
        date: '2026-07-06T13:25:00+05:00',
        helpfulCount: 9,
        isVerified: true,
      },
      {
        id: 'rev-015',
        userId: 'usr-115',
        userName: 'Tahir Mehmood',
        userVehicle: 'MG ZS EV',
        rating: 4,
        comment:
          'Do not come here if you are in a hurry — it is AC only, so a 20 to 80 percent run takes the better part of three hours. Priced accordingly and well maintained.',
        date: '2026-06-14T12:40:00+05:00',
        helpfulCount: 17,
        isVerified: false,
      },
    ],
  },
  {
    id: 'stn-005',
    slug: 'blue-area-ev-station-islamabad',
    name: 'Blue Area EV Station',
    description:
      'Two-bay 150 kW site on Jinnah Avenue. Currently offline for a transformer upgrade — the operator expects to restore service in August 2026.',
    address: {
      street: 'Jinnah Avenue, Blue Area',
      area: 'Blue Area',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.7089, lng: 73.0641 },
    connectors: [
      {
        id: 'stn-005-c1',
        type: 'CCS2',
        maxPowerKw: 150,
        ports: 2,
        availablePorts: 0,
        pricePerKwh: 80,
        isFree: false,
        status: 'offline',
        compatibleVehicles: ['BYD Seal', 'BYD Han', 'BMW iX', 'Mercedes EQS', 'KIA EV6'],
      },
      {
        id: 'stn-005-c2',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 0,
        pricePerKwh: 50,
        pricePerHour: 240,
        isFree: false,
        status: 'offline',
        compatibleVehicles: ['BYD Atto 3', 'BMW i4', 'Mercedes EQS'],
      },
    ],
    amenities: [
      { type: 'restaurant', available: true },
      { type: 'cafe', available: true },
      { type: 'parking', available: true, note: 'Paid underground parking' },
      { type: 'prayer', available: true },
      { type: 'washroom', available: true },
      { type: 'shopping', available: false },
      { type: 'wifi', available: false },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: ['/images/stations/blue-area-ev-station-1.jpg'],
    coverPhoto: '/images/stations/blue-area-ev-station-1.jpg',
    rating: 4.0,
    reviewCount: 37,
    status: 'offline',
    isVerified: true,
    network: 'Renergent',
    createdAt: '2025-05-09T14:15:00+05:00',
    updatedAt: '2026-07-27T10:05:00+05:00',
    reviews: [
      {
        id: 'rev-016',
        userId: 'usr-116',
        userName: 'Adeel Hussain',
        userVehicle: 'BYD Seal',
        rating: 4,
        comment:
          'Was a genuinely fast site before it went down — 130 kW sustained on my Seal. Currently offline for a transformer upgrade, so check the app before driving over.',
        date: '2026-07-18T17:10:00+05:00',
        helpfulCount: 28,
        isVerified: true,
      },
      {
        id: 'rev-017',
        userId: 'usr-117',
        userName: 'Sadia Iqbal',
        userVehicle: 'Mercedes EQS',
        rating: 4,
        comment:
          'Turned up on a Sunday with both bays dead and no notice on site. Staff at the plaza confirmed it has been down for a few weeks. Please update the status board.',
        date: '2026-07-12T11:50:00+05:00',
        helpfulCount: 33,
        isVerified: true,
      },
      {
        id: 'rev-018',
        userId: 'usr-118',
        userName: 'Farhan Qureshi',
        userVehicle: 'BMW iX',
        rating: 4,
        comment:
          'Excellent location right on Jinnah Avenue and the hardware is good quality. Docking a star only for the current outage — worth revisiting once it is back.',
        date: '2026-06-25T09:35:00+05:00',
        helpfulCount: 15,
        isVerified: false,
      },
    ],
  },
  {
    id: 'stn-006',
    slug: 'dha-charging-hub-karachi',
    name: 'DHA Charging Hub',
    description:
      'The only public CHAdeMO in Karachi alongside a 120 kW CCS2 bay, making it the go-to site for imported Nissan Leafs as well as newer CCS2 cars.',
    address: {
      street: 'Khayaban-e-Ittehad, Phase 6',
      area: 'DHA Phase 6',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75500',
    },
    coordinates: { lat: 24.7983, lng: 67.0531 },
    connectors: [
      {
        id: 'stn-006-c1',
        type: 'CCS2',
        maxPowerKw: 120,
        ports: 2,
        availablePorts: 2,
        pricePerKwh: 76,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'BYD Seal', 'MG ZS EV', 'Hyundai Ioniq 5', 'BMW iX'],
      },
      {
        id: 'stn-006-c2',
        type: 'CHAdeMO',
        maxPowerKw: 50,
        ports: 1,
        availablePorts: 1,
        pricePerKwh: 70,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['Nissan Leaf', 'Nissan Leaf e+', 'Mitsubishi Outlander PHEV'],
      },
      {
        id: 'stn-006-c3',
        type: 'Type2',
        maxPowerKw: 22,
        ports: 2,
        availablePorts: 1,
        pricePerKwh: 47,
        pricePerHour: 210,
        isFree: false,
        status: 'available',
        compatibleVehicles: ['BYD Atto 3', 'MG HS PHEV', 'BMW i4'],
      },
    ],
    amenities: [
      { type: 'cafe', available: true, note: 'Two cafés in the same commercial strip' },
      { type: 'restaurant', available: true },
      { type: 'washroom', available: true },
      { type: 'wifi', available: true },
      { type: 'parking', available: true, note: 'Dedicated EV bays, enforced by security' },
      { type: 'prayer', available: true },
      { type: 'shopping', available: true },
      { type: 'hotel', available: false },
    ],
    operatingHours: HOURS_24_7,
    photos: [
      '/images/stations/dha-charging-hub-1.jpg',
      '/images/stations/dha-charging-hub-2.jpg',
      '/images/stations/dha-charging-hub-3.jpg',
    ],
    coverPhoto: '/images/stations/dha-charging-hub-1.jpg',
    rating: 4.9,
    reviewCount: 176,
    status: 'available',
    isVerified: true,
    network: 'Shell Recharge',
    phone: '+92 21 3584 9022',
    businessId: 'biz-003',
    createdAt: '2024-06-28T08:00:00+05:00',
    updatedAt: '2026-07-30T06:30:00+05:00',
    reviews: [
      {
        id: 'rev-019',
        userId: 'usr-119',
        userName: 'Omar Faridi',
        userVehicle: 'Nissan Leaf e+',
        rating: 5,
        comment:
          'The only reliable public CHAdeMO in the city. As a Leaf owner this station is the reason long trips inside Karachi are practical at all. Never found it broken.',
        date: '2026-07-28T10:30:00+05:00',
        helpfulCount: 41,
        isVerified: true,
      },
      {
        id: 'rev-020',
        userId: 'usr-120',
        userName: 'Nida Aslam',
        userVehicle: 'BYD Seal',
        rating: 5,
        comment:
          'Six ports across three standards means zero waiting, even at peak. Dedicated bays are actually enforced by security so you never find a petrol car parked in one.',
        date: '2026-07-20T19:45:00+05:00',
        helpfulCount: 27,
        isVerified: true,
      },
      {
        id: 'rev-021',
        userId: 'usr-121',
        userName: 'Junaid Sattar',
        userVehicle: 'Hyundai Ioniq 5',
        rating: 5,
        comment:
          'Consistent 115 kW on the CCS2 side and the site is spotless. Cafés next door make the 25 minute stop painless. Best charging experience in Karachi by a wide margin.',
        date: '2026-07-13T14:15:00+05:00',
        helpfulCount: 19,
        isVerified: true,
      },
      {
        id: 'rev-022',
        userId: 'usr-122',
        userName: 'Sarah Ashraf',
        userVehicle: 'MG ZS EV',
        rating: 5,
        comment:
          'Well lit, staffed around the clock and the app shows live port availability that actually matches reality. Slightly pricier per unit but worth it for the reliability.',
        date: '2026-07-01T21:00:00+05:00',
        helpfulCount: 14,
        isVerified: false,
      },
      {
        id: 'rev-023',
        userId: 'usr-123',
        userName: 'Waqas Ahmed',
        userVehicle: 'BYD Atto 3',
        rating: 4,
        comment:
          'Hard to fault the hardware or the service. Only reason for four stars is the tariff — about 10 rupees a unit more than Clifton, which adds up on a full charge.',
        date: '2026-06-22T16:20:00+05:00',
        helpfulCount: 11,
        isVerified: true,
      },
    ],
  },
]

// ─── EV Models ───────────────────────────────────────

export const MOCK_EV_MODELS: EVModel[] = [
  {
    id: 'ev-001',
    make: 'BYD',
    model: 'Atto 3',
    year: 2024,
    rangeKm: 480,
    batteryCapacityKwh: 60.5,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 88,
  },
  {
    id: 'ev-002',
    make: 'BYD',
    model: 'Seal',
    year: 2024,
    rangeKm: 580,
    batteryCapacityKwh: 82.5,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 150,
  },
  {
    id: 'ev-003',
    make: 'BYD',
    model: 'Han',
    year: 2023,
    rangeKm: 521,
    batteryCapacityKwh: 85.4,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 120,
  },
  {
    id: 'ev-004',
    make: 'MG',
    model: 'ZS EV',
    year: 2024,
    rangeKm: 440,
    batteryCapacityKwh: 50.3,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 76,
  },
  {
    id: 'ev-005',
    make: 'Changan',
    model: 'Lumin',
    year: 2024,
    rangeKm: 301,
    batteryCapacityKwh: 32.8,
    connectorTypes: ['GBT'],
    chargingSpeedKw: 40,
  },
  {
    id: 'ev-006',
    make: 'Proton',
    model: 'e.MAS 7',
    year: 2024,
    rangeKm: 430,
    batteryCapacityKwh: 60.2,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 80,
  },
  {
    id: 'ev-007',
    make: 'BMW',
    model: 'i4',
    year: 2023,
    rangeKm: 590,
    batteryCapacityKwh: 83.9,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 205,
  },
  {
    id: 'ev-008',
    make: 'BMW',
    model: 'iX',
    year: 2023,
    rangeKm: 630,
    batteryCapacityKwh: 111.5,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 195,
  },
  {
    id: 'ev-009',
    make: 'Mercedes',
    model: 'EQS',
    year: 2023,
    rangeKm: 770,
    batteryCapacityKwh: 107.8,
    connectorTypes: ['CCS2', 'Type2'],
    chargingSpeedKw: 200,
  },
  {
    id: 'ev-010',
    make: 'Nissan',
    model: 'Leaf e+',
    year: 2022,
    rangeKm: 385,
    batteryCapacityKwh: 62,
    connectorTypes: ['CHAdeMO', 'Type1'],
    chargingSpeedKw: 100,
  },
]

// ─── EV Services ─────────────────────────────────────
export const MOCK_SERVICES: EVService[] = [
  {
    id: 'svc-001',
    slug: 'byd-pakistan-official-dealer',
    name: 'BYD Pakistan Official Dealer',
    category: 'dealership',
    description:
      'Authorised BYD showroom on Shahrah-e-Faisal covering the Atto 3, Seal and Dolphin. Test drives by appointment, on-site finance desk and a dedicated delivery bay.',
    address: {
      street: 'Shahrah-e-Faisal, near Nursery',
      area: 'PECHS',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75400',
    },
    coordinates: { lat: 24.8607, lng: 67.0641 },
    phone: '0300-2145880',
    email: 'karachi@bydpakistan.example',
    website: 'https://byd.example.pk/karachi',
    photos: [],
    rating: 4.7,
    reviewCount: 128,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2024-09-12T10:00:00+05:00',
  },
  {
    id: 'svc-002',
    slug: 'mg-motors-pakistan',
    name: 'MG Motors Pakistan',
    category: 'dealership',
    description:
      'MG flagship showroom on Main Boulevard Gulberg with the ZS EV and MG4 on display. Handles bookings, trade-ins and extended warranty registration.',
    address: {
      street: 'Main Boulevard, Gulberg II',
      area: 'Gulberg',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54660',
    },
    coordinates: { lat: 31.5102, lng: 74.3441 },
    phone: '0300-8442190',
    email: 'lahore@mgmotors.example',
    website: 'https://mgmotors.example.pk',
    photos: [],
    rating: 4.5,
    reviewCount: 96,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2024-10-03T09:30:00+05:00',
  },
  {
    id: 'svc-003',
    slug: 'ev-care-workshop',
    name: 'EV Care Workshop',
    category: 'service-center',
    description:
      'High-voltage certified workshop in I-9 handling battery diagnostics, thermal system service and warranty repairs for BYD, MG and imported Japanese EVs.',
    address: {
      street: 'Plot 22, I-9 Industrial Area',
      area: 'I-9',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.6607, lng: 73.0479 },
    phone: '0300-5119042',
    email: 'service@evcare.example',
    photos: [],
    rating: 4.8,
    reviewCount: 74,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2024-12-01T08:45:00+05:00',
  },
  {
    id: 'svc-004',
    slug: 'green-auto-services',
    name: 'Green Auto Services',
    category: 'service-center',
    description:
      'Independent EV specialist in Model Town offering software updates, brake and suspension work, and pre-purchase inspections for used electric vehicles.',
    address: {
      street: 'Block C, Model Town Link Road',
      area: 'Model Town',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54700',
    },
    coordinates: { lat: 31.4818, lng: 74.3239 },
    phone: '0300-4270615',
    email: 'hello@greenauto.example',
    photos: [],
    rating: 4.4,
    reviewCount: 52,
    operatingHours: HOURS_BUSINESS,
    isVerified: false,
    createdAt: '2025-01-18T10:15:00+05:00',
  },
  {
    id: 'svc-005',
    slug: 'homecharge-pakistan',
    name: 'HomeCharge Pakistan',
    category: 'home-charger-installer',
    description:
      'Certified installers for 7.4 kW and 22 kW wallboxes across Karachi. Includes load assessment, dedicated breaker, earthing check and K-Electric compliance paperwork.',
    address: {
      street: 'Office 5, Bahadurabad Commercial',
      area: 'Bahadurabad',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '74800',
    },
    coordinates: { lat: 24.8801, lng: 67.0673 },
    phone: '0300-2938471',
    email: 'install@homecharge.example',
    website: 'https://homecharge.example.pk',
    photos: [],
    rating: 4.9,
    reviewCount: 61,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2025-02-05T09:30:00+05:00',
  },
  {
    id: 'svc-006',
    slug: 'ev-install-pro',
    name: 'EV Install Pro',
    category: 'home-charger-installer',
    description:
      'Home and workplace charger installation across Islamabad and Rawalpindi, including smart charger configuration and solar-linked charging setups.',
    address: {
      street: 'Office 12, Kohistan Plaza, I-8 Markaz',
      area: 'I-8',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.6706, lng: 73.0752 },
    phone: '0300-8560733',
    email: 'info@evinstallpro.example',
    website: 'https://evinstallpro.example.pk',
    photos: [],
    rating: 4.6,
    reviewCount: 38,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2025-03-11T11:00:00+05:00',
  },
  {
    id: 'svc-007',
    slug: 'plug-store-pk',
    name: 'Plug Store PK',
    category: 'accessories',
    description:
      'Charging cables, portable chargers, CCS2 and Type 2 adapters, and EV-specific detailing supplies. Ships nationwide with same-day pickup in Lahore.',
    address: {
      street: 'Shop 14, Fortress Stadium',
      area: 'Cantt',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54810',
    },
    coordinates: { lat: 31.5497, lng: 74.3736 },
    phone: '0300-4118256',
    email: 'orders@plugstore.example',
    website: 'https://plugstore.example.pk',
    photos: [],
    rating: 4.3,
    reviewCount: 143,
    operatingHours: HOURS_MALL,
    isVerified: false,
    createdAt: '2024-11-22T12:00:00+05:00',
  },
  {
    id: 'svc-008',
    slug: 'ev-gadgets-pakistan',
    name: 'EV Gadgets Pakistan',
    category: 'accessories',
    description:
      'Dash cams, tyre inflators, seat covers and granny cables for imported EVs. Stocks CHAdeMO adapters that are hard to find elsewhere in the country.',
    address: {
      street: 'Shop 31, Dolmen Mall Clifton',
      area: 'Clifton',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '75600',
    },
    coordinates: { lat: 24.8138, lng: 67.0311 },
    phone: '0300-2664019',
    email: 'support@evgadgets.example',
    photos: [],
    rating: 4.2,
    reviewCount: 87,
    operatingHours: HOURS_MALL,
    isVerified: false,
    createdAt: '2025-01-09T13:20:00+05:00',
  },
  {
    id: 'svc-009',
    slug: 'ev-shield-insurance',
    name: 'EV Shield Insurance',
    category: 'insurance',
    description:
      'EV-specific comprehensive cover including battery pack protection, charging equipment and home wallbox. Online claims with a dedicated EV assessor.',
    address: {
      street: 'Jinnah Avenue, Blue Area',
      area: 'Blue Area',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.7089, lng: 73.0641 },
    phone: '0300-5024178',
    email: 'cover@evshield.example',
    website: 'https://evshield.example.pk',
    photos: [],
    rating: 4.5,
    reviewCount: 44,
    operatingHours: HOURS_BUSINESS,
    isVerified: true,
    createdAt: '2025-02-27T09:00:00+05:00',
  },
  {
    id: 'svc-010',
    slug: 'green-cover-insurance',
    name: 'Green Cover Insurance',
    category: 'insurance',
    description:
      'Motor cover with a no-claims discount that carries over from petrol policies, plus optional roadside assistance and third-party-only plans for older imports.',
    address: {
      street: '4th Floor, Kalma Chowk Tower',
      area: 'Gulberg III',
      city: 'Lahore',
      province: 'Punjab',
      country: 'Pakistan',
      postalCode: '54660',
    },
    coordinates: { lat: 31.5013, lng: 74.3336 },
    phone: '0300-4783290',
    email: 'policies@greencover.example',
    photos: [],
    rating: 4.1,
    reviewCount: 29,
    operatingHours: HOURS_BUSINESS,
    isVerified: false,
    createdAt: '2025-04-14T10:40:00+05:00',
  },
  {
    id: 'svc-011',
    slug: 'ev-rescue-pakistan',
    name: 'EV Rescue Pakistan',
    category: 'roadside-assistance',
    description:
      'Round-the-clock recovery for electric vehicles across Karachi, with flatbed towing that avoids drivetrain damage and a mobile charging van for flat batteries.',
    address: {
      street: 'Plot 88, Korangi Industrial Area',
      area: 'Korangi',
      city: 'Karachi',
      province: 'Sindh',
      country: 'Pakistan',
      postalCode: '74900',
    },
    coordinates: { lat: 24.8322, lng: 67.1319 },
    phone: '0300-2007311',
    email: 'dispatch@evrescue.example',
    website: 'https://evrescue.example.pk',
    photos: [],
    rating: 4.6,
    reviewCount: 112,
    operatingHours: HOURS_24_7,
    isVerified: true,
    createdAt: '2024-08-30T07:00:00+05:00',
  },
  {
    id: 'svc-012',
    slug: '24-7-ev-assist',
    name: '24/7 EV Assist',
    category: 'roadside-assistance',
    description:
      'Motorway and city recovery covering Islamabad, Rawalpindi and the M-2 corridor. Jump starts, lockout service, tyre assistance and emergency top-up charging.',
    address: {
      street: 'Service Road, G-11 Markaz',
      area: 'G-11',
      city: 'Islamabad',
      province: 'Islamabad Capital Territory',
      country: 'Pakistan',
      postalCode: '44000',
    },
    coordinates: { lat: 33.668, lng: 72.971 },
    phone: '0300-5567824',
    email: 'help@evassist.example',
    photos: [],
    rating: 4.4,
    reviewCount: 67,
    operatingHours: HOURS_24_7,
    isVerified: true,
    createdAt: '2025-05-02T08:15:00+05:00',
  },
]
// ─── Community Posts ─────────────────────────────────

export const MOCK_POSTS: CommunityPost[] = [
  {
    id: 'post-001',
    slug: 'lahore-to-islamabad-in-a-byd-atto-3-one-stop',
    userId: 'usr-101',
    userName: 'Ahmed Raza',
    userVehicle: 'BYD Atto 3',
    title: 'Lahore to Islamabad in an Atto 3 — one stop, 4h 55m door to door',
    content:
      'Did the M-2 run on Saturday and it is now genuinely a one-stop trip. Left Lahore at 92 percent, sat at 110 km/h with the AC on, and rolled into the Bhera service area with 34 percent left after 265 km.\n\nCharged for 28 minutes to 78 percent, which was more than enough for the remaining 110 km plus city driving. Total door to door was 4 hours 55 minutes including the stop, so maybe 20 minutes more than I would have taken in a petrol car.\n\nTwo things worth knowing. Real-world consumption at motorway speed was 17.8 kWh/100km, noticeably worse than the 15.2 I see around town, so do not plan on the NEDC number. And the fast charger at Bhera tapers hard past 80 percent, so it is quicker to leave at 78 and stop again than to wait it out.',
    category: 'trip-report',
    photos: [
      '/images/community/m2-trip-1.jpg',
      '/images/community/m2-trip-2.jpg',
    ],
    likeCount: 214,
    commentCount: 3,
    createdAt: '2026-07-26T20:15:00+05:00',
    updatedAt: '2026-07-26T20:15:00+05:00',
    comments: [
      {
        id: 'cmt-001',
        postId: 'post-001',
        userId: 'usr-107',
        userName: 'Hassan Ali',
        content:
          'This matches my experience almost exactly in a ZS EV, except I need two stops because of the smaller battery. The taper point on the Bhera unit is the key detail — took me three trips to work that out.',
        likeCount: 27,
        createdAt: '2026-07-26T21:40:00+05:00',
      },
      {
        id: 'cmt-002',
        postId: 'post-001',
        userId: 'usr-106',
        userName: 'Zainab Malik',
        content:
          'Did you try 100 km/h instead of 110? On my Han the drop from 120 to 100 is worth nearly 60 km of range, which is often cheaper than the extra charging stop.',
        likeCount: 15,
        createdAt: '2026-07-27T09:05:00+05:00',
      },
      {
        id: 'cmt-003',
        postId: 'post-001',
        userId: 'usr-113',
        userName: 'Saad Rehman',
        content:
          'Useful writeup. Worth adding that the Bhera site only has two working ports, so on Eid weekends there was a 40 minute queue. Mall Road hub before you leave Lahore is a safer bet.',
        likeCount: 22,
        createdAt: '2026-07-27T13:30:00+05:00',
      },
    ],
  },
  {
    id: 'post-002',
    slug: 'six-months-with-an-mg-zs-ev-running-costs',
    userId: 'usr-102',
    userName: 'Fatima Khan',
    userVehicle: 'MG ZS EV',
    title: 'Six months and 11,000 km with a ZS EV — actual running costs',
    content:
      'I kept every charging receipt since January, so here are real numbers rather than estimates.\n\nOf 11,000 km, roughly 70 percent was charged at home on a 7.4 kW wallbox and 30 percent on public DC. Home charging worked out to about 42 rupees per unit on the protected slab, public DC averaged 71. Blended cost came to 3.4 rupees per kilometre.\n\nMy old 1.6 Corolla was doing about 12 km per litre, so call it 22 rupees per kilometre. Over 11,000 km that is a saving of roughly 205,000 rupees in fuel alone.\n\nThe honest caveats: I have had one unplanned service visit for a coolant pump, load-shedding means I sometimes cannot charge overnight, and resale value on EVs here is still an unknown. But on running cost the case is not close.',
    category: 'vehicle-review',
    photos: ['/images/community/zs-ev-costs-1.jpg'],
    likeCount: 389,
    commentCount: 2,
    createdAt: '2026-07-18T11:20:00+05:00',
    updatedAt: '2026-07-19T08:05:00+05:00',
    comments: [
      {
        id: 'cmt-004',
        postId: 'post-002',
        userId: 'usr-115',
        userName: 'Tahir Mehmood',
        content:
          'Thank you for using real receipts instead of the usual per-100km guesswork. The 3.4 rupees per km figure lines up with what I calculated over a shorter period.',
        likeCount: 41,
        createdAt: '2026-07-18T14:50:00+05:00',
      },
      {
        id: 'cmt-005',
        postId: 'post-002',
        userId: 'usr-111',
        userName: 'Kamran Aslam',
        content:
          'Worth noting the protected slab only applies under 200 units a month. Once you cross that, home charging jumps closer to 60 a unit and the maths changes for anyone driving more than you.',
        likeCount: 36,
        createdAt: '2026-07-19T07:15:00+05:00',
      },
    ],
  },
  {
    id: 'post-003',
    slug: 'which-connector-should-i-look-for-buying-first-ev',
    userId: 'usr-110',
    userName: 'Hina Butt',
    userVehicle: 'MG ZS EV',
    title: 'Buying your first EV in Pakistan? Check the connector before anything else',
    content:
      'Seeing a lot of posts from people about to buy an imported EV without checking what they can actually plug into, so here is the short version.\n\nCCS2 is the safe choice. Almost every new public DC charger going up in Lahore, Islamabad and Karachi is CCS2, and every locally sold BYD, MG and Proton uses it.\n\nCHAdeMO is the risk. It is fine if you are buying an imported Leaf and you live near DHA in Karachi, but there is essentially one reliable public CHAdeMO in the entire city. Anywhere else and you are on home AC charging only.\n\nGB/T shows up on some directly imported Chinese cars. Public GB/T is close to non-existent here, so treat those as home-charge-only vehicles.\n\nType 2 is the AC standard and every modern EV has it. Slow, but universal — useful as a fallback everywhere.\n\nBefore you commit to a car, open the map, filter by its connector, and look at what is within 20 km of your home and office. If the answer is one station, think carefully.',
    category: 'buying-advice',
    likeCount: 502,
    commentCount: 2,
    createdAt: '2026-07-08T16:45:00+05:00',
    updatedAt: '2026-07-08T16:45:00+05:00',
    comments: [
      {
        id: 'cmt-006',
        postId: 'post-003',
        userId: 'usr-119',
        userName: 'Omar Faridi',
        content:
          'Leaf owner here and this is fair. I love the car and DHA Charging Hub has never let me down, but if I lived in Lahore I would not have bought it. Buy the connector, not just the car.',
        likeCount: 88,
        createdAt: '2026-07-08T19:30:00+05:00',
      },
      {
        id: 'cmt-007',
        postId: 'post-003',
        userId: 'usr-112',
        userName: 'Maryam Farooq',
        content:
          'Would add one thing for GB/T owners like me: a decent portable AC charger is not optional, it is part of the purchase price. Budget for it up front.',
        likeCount: 45,
        createdAt: '2026-07-09T10:10:00+05:00',
      },
    ],
  },
  {
    id: 'post-004',
    slug: 'best-fast-charger-in-karachi-right-now',
    userId: 'usr-119',
    userName: 'Omar Faridi',
    userVehicle: 'Nissan Leaf e+',
    title: 'Best fast charger in Karachi right now?',
    content:
      'Moved to DHA last month and still working out where to charge reliably. So far DHA Charging Hub has been the only one I trust — six ports, never queued, and the CHAdeMO actually works, which matters because my Leaf cannot use anything else.\n\nClifton Fast Charge is closer to my office but one of its two ports has been dead for weeks and 50 kW is slow for a 62 kWh pack.\n\nAnyone found something better on the far side of the city? Ideally somewhere near Korangi or SITE. Happy to pay more per unit for something that is actually working when I arrive.',
    category: 'charging-experience',
    likeCount: 45,
    commentCount: 28,
    createdAt: '2026-07-27T09:20:00+05:00',
    updatedAt: '2026-07-27T09:20:00+05:00',
    comments: [
      {
        id: 'cmt-008',
        postId: 'post-004',
        userId: 'usr-120',
        userName: 'Nida Aslam',
        content:
          'DHA is the right answer for CHAdeMO, full stop. Nothing else in Karachi is reliable for it. For CCS2 I would add the new site off Shahrah-e-Faisal but it only opened three weeks ago so treat it as unproven.',
        likeCount: 19,
        createdAt: '2026-07-27T11:45:00+05:00',
      },
      {
        id: 'cmt-009',
        postId: 'post-004',
        userId: 'usr-123',
        userName: 'Waqas Ahmed',
        content:
          'Clifton has been half-broken since June. I reported it twice through the app. Worth calling ahead rather than driving there on faith.',
        likeCount: 14,
        createdAt: '2026-07-27T15:10:00+05:00',
      },
      {
        id: 'cmt-010',
        postId: 'post-004',
        userId: 'usr-121',
        userName: 'Junaid Sattar',
        content:
          'Nothing usable near Korangi or SITE yet as far as I know. The industrial areas are a real gap — plenty of EVs going in and out for work and no public charging at all.',
        likeCount: 11,
        createdAt: '2026-07-28T08:30:00+05:00',
      },
    ],
  },
  {
    id: 'post-005',
    slug: 'mg-zs-ev-vs-byd-atto-3-which-should-i-buy',
    userId: 'usr-107',
    userName: 'Hassan Ali',
    userVehicle: 'MG ZS EV',
    title: 'MG ZS EV vs BYD Atto 3 — Which should I buy?',
    content:
      'I own the ZS EV and my brother is about to buy his first EV, so I have spent a lot of time comparing these two lately. Here is my honest take having driven both.\n\nThe Atto 3 wins on battery. 60.5 kWh against the ZS EV 50.3 kWh is a real difference on intercity runs — roughly one fewer stop between Lahore and Islamabad. Build quality inside is also a step up.\n\nThe ZS EV wins on price and on service network. MG has more workshops in more cities, and when something needs fixing that matters more than people expect.\n\nCharging speed is closer than the spec sheets suggest. The Atto 3 peaks higher but both taper hard past 60 percent on the chargers we actually have here.\n\nIf you drive mostly in-city and want the lower price, ZS EV. If you regularly do long runs, Atto 3.',
    category: 'buying-advice',
    likeCount: 124,
    commentCount: 67,
    createdAt: '2026-07-25T14:00:00+05:00',
    updatedAt: '2026-07-25T14:00:00+05:00',
    comments: [
      {
        id: 'cmt-011',
        postId: 'post-005',
        userId: 'usr-101',
        userName: 'Ahmed Raza',
        content:
          'Atto 3 owner here and I agree with all of this. The one thing I would add is boot space — the Atto 3 is noticeably more practical if you carry anything regularly.',
        likeCount: 38,
        createdAt: '2026-07-25T16:20:00+05:00',
      },
      {
        id: 'cmt-012',
        postId: 'post-005',
        userId: 'usr-115',
        userName: 'Tahir Mehmood',
        content:
          'The service network point is underrated. I waited eleven days for a part on a less common brand. Whatever you buy, check where the nearest authorised workshop actually is.',
        likeCount: 44,
        createdAt: '2026-07-26T09:05:00+05:00',
      },
      {
        id: 'cmt-013',
        postId: 'post-005',
        userId: 'usr-113',
        userName: 'Saad Rehman',
        content:
          'Would also factor in resale. Neither has a long track record here yet, so whatever you buy, assume the first few years of depreciation are unknown.',
        likeCount: 21,
        createdAt: '2026-07-26T13:40:00+05:00',
      },
    ],
  },
  {
    id: 'post-006',
    slug: 'new-ev-policy-announced-by-government',
    userId: 'usr-106',
    userName: 'Zainab Malik',
    userVehicle: 'BYD Han',
    title: 'New EV policy announced by Government',
    content:
      'The updated policy landed this week and there are a few things worth reading carefully rather than from the headlines.\n\nDuty relief on imported EVs has been extended, which should hold prices roughly where they are rather than pushing them down much further.\n\nMore interesting is the charging infrastructure clause — new commercial buildings above a certain size will need to provision for EV charging at the design stage. That is the sort of thing that takes three years to show up but changes the map permanently.\n\nWhat is still missing is anything meaningful on grid capacity. Every operator I have spoken to says the transformer, not the charger, is the bottleneck.',
    category: 'ev-news',
    likeCount: 203,
    commentCount: 89,
    createdAt: '2026-07-29T08:00:00+05:00',
    updatedAt: '2026-07-29T10:15:00+05:00',
    comments: [
      {
        id: 'cmt-014',
        postId: 'post-006',
        userId: 'usr-116',
        userName: 'Adeel Hussain',
        content:
          'The building provision clause is the real story here. Right now retrofitting a charger into an existing plaza is the single biggest cost for any operator.',
        likeCount: 57,
        createdAt: '2026-07-29T09:30:00+05:00',
      },
      {
        id: 'cmt-015',
        postId: 'post-006',
        userId: 'usr-117',
        userName: 'Sadia Iqbal',
        content:
          'Agreed on grid capacity. Blue Area has been offline for weeks for a transformer upgrade — that is the constraint, not the number of chargers.',
        likeCount: 41,
        createdAt: '2026-07-29T12:00:00+05:00',
      },
    ],
  },
  {
    id: 'post-007',
    slug: 'my-first-month-with-byd-atto-3',
    userId: 'usr-104',
    userName: 'Ayesha Siddiqui',
    userVehicle: 'BYD Seal',
    title: 'My first month with BYD Atto 3',
    content:
      'Thirty days and about 1,400 km in. Short version: I would buy it again, with two caveats.\n\nWhat works. The ride is genuinely comfortable on bad roads, which matters more here than any performance figure. Charging at home overnight has completely removed the fuel-station routine from my week. Consumption has settled at 16.2 kWh/100km in mixed driving.\n\nWhat does not. The infotainment rotates the screen as a party trick and is slower than it should be. And the regenerative braking has two settings, neither of which is proper one-pedal driving.\n\nThe caveats: you need home charging for this to make sense, and you need to accept that long trips still require planning.',
    category: 'vehicle-review',
    likeCount: 67,
    commentCount: 23,
    createdAt: '2026-07-22T18:30:00+05:00',
    updatedAt: '2026-07-22T18:30:00+05:00',
    comments: [
      {
        id: 'cmt-016',
        postId: 'post-007',
        userId: 'usr-102',
        userName: 'Fatima Khan',
        content:
          'The one-pedal point is fair. Coming from a ZS EV I found the Atto 3 regen weaker than expected. You adapt but it is not the same.',
        likeCount: 15,
        createdAt: '2026-07-23T08:10:00+05:00',
      },
    ],
  },
  {
    id: 'post-008',
    slug: 'home-charger-installation-what-it-actually-costs',
    userId: 'usr-113',
    userName: 'Saad Rehman',
    userVehicle: 'BYD Atto 3',
    title: 'Home charger installation — what it actually costs',
    content:
      'Just had a 7.4 kW wallbox installed in Lahore and there is very little honest information about pricing, so here are my real numbers.\n\nCharger unit: 148,000. Installation labour: 22,000. Dedicated 40A breaker and cabling for an 18 metre run: 31,000. Earthing rod, because the existing one was not adequate: 9,000.\n\nTotal: 210,000 rupees.\n\nThe thing nobody warned me about is the earthing. Two of the three installers I got quotes from did not even mention it. Ask about it explicitly — a wallbox on poor earthing is a genuine safety problem, not a technicality.',
    category: 'general',
    likeCount: 156,
    commentCount: 41,
    createdAt: '2026-07-20T11:00:00+05:00',
    updatedAt: '2026-07-20T11:00:00+05:00',
    comments: [
      {
        id: 'cmt-017',
        postId: 'post-008',
        userId: 'usr-111',
        userName: 'Kamran Aslam',
        content:
          'This matches my costs in Karachi almost exactly, within about 15,000. And yes on earthing — my installer replaced the rod as a matter of course and I did not understand why until later.',
        likeCount: 33,
        createdAt: '2026-07-20T14:25:00+05:00',
      },
      {
        id: 'cmt-018',
        postId: 'post-008',
        userId: 'usr-109',
        userName: 'Imran Sheikh',
        content:
          'Worth adding: check your meter capacity before ordering the charger. Mine needed upgrading first and that added three weeks.',
        likeCount: 27,
        createdAt: '2026-07-21T09:50:00+05:00',
      },
    ],
  },
  {
    id: 'post-009',
    slug: 'karachi-to-hyderabad-and-back-on-one-charge',
    userId: 'usr-120',
    userName: 'Nida Aslam',
    userVehicle: 'BYD Seal',
    title: 'Karachi to Hyderabad and back on one charge',
    content:
      'Did the round trip on Sunday — 162 km each way on the M-9, so 324 km total — without stopping to charge. Left at 96 percent, got home on 19 percent.\n\nThe motorway is flat and the surface is good, so consumption was better than I expected at 17.1 kWh/100km sitting at 110 km/h with the AC running properly.\n\nIf you have a smaller pack this is comfortably a one-stop trip. There is nothing usable in Hyderabad itself yet, so plan on charging before you leave Karachi either way.',
    category: 'trip-report',
    likeCount: 78,
    commentCount: 19,
    createdAt: '2026-07-19T20:00:00+05:00',
    updatedAt: '2026-07-19T20:00:00+05:00',
    comments: [
      {
        id: 'cmt-019',
        postId: 'post-009',
        userId: 'usr-110',
        userName: 'Hina Butt',
        content:
          'Confirming there is still nothing public in Hyderabad. I did this trip in a ZS EV and had to charge at a hotel on a 3-pin, which took most of the afternoon.',
        likeCount: 22,
        createdAt: '2026-07-20T07:15:00+05:00',
      },
    ],
  },
  {
    id: 'post-010',
    slug: 'charging-etiquette-we-need-to-talk-about-it',
    userId: 'usr-105',
    userName: 'Usman Tariq',
    userVehicle: 'KIA EV6',
    title: 'Charging etiquette — we need to talk about it',
    content:
      'Three times this month I have arrived at a charger to find a car sitting at 100 percent with the owner nowhere nearby. Once for over an hour.\n\nWe are a small enough community that this is still fixable by norms rather than rules. A few suggestions.\n\nMove your car when it is done, or at least be reachable. Do not use a 150 kW bay for a top-up you could do on AC. If someone is waiting and you are past 80 percent, the taper means you are giving up very little by unplugging.\n\nNone of this is difficult and it stops being a problem entirely if we all just do it.',
    category: 'general',
    likeCount: 189,
    commentCount: 52,
    createdAt: '2026-07-17T16:45:00+05:00',
    updatedAt: '2026-07-17T16:45:00+05:00',
    comments: [
      {
        id: 'cmt-020',
        postId: 'post-010',
        userId: 'usr-103',
        userName: 'Bilal Ahmad',
        content:
          'Strongly agree on the 80 percent point. Past that the curve is so flat you are holding a bay hostage for almost no added range.',
        likeCount: 48,
        createdAt: '2026-07-17T19:20:00+05:00',
      },
      {
        id: 'cmt-021',
        postId: 'post-010',
        userId: 'usr-122',
        userName: 'Sarah Ashraf',
        content:
          'Some operators abroad charge an idle fee after the session ends. Might be worth suggesting to the networks here before it becomes a bigger problem.',
        likeCount: 35,
        createdAt: '2026-07-18T10:05:00+05:00',
      },
    ],
  },
  {
    id: 'post-011',
    slug: 'winter-range-loss-what-to-expect-in-northern-pakistan',
    userId: 'usr-118',
    userName: 'Farhan Qureshi',
    userVehicle: 'BMW iX',
    title: 'Winter range loss — what to expect in northern Pakistan',
    content:
      'With Murree and Naran trips coming up for a lot of people, worth setting expectations on cold weather.\n\nIn Islamabad at around 5 degrees I lose roughly 15 percent against my summer average. Above Murree, closer to freezing, it has been nearer 25 percent — and that is before the climbing, which costs more again.\n\nThe practical advice: precondition the cabin while still plugged in, use seat heating rather than blasting the cabin heater, and treat the trip computer as optimistic until you are back below the snow line.',
    category: 'trip-report',
    likeCount: 94,
    commentCount: 31,
    createdAt: '2026-07-14T12:30:00+05:00',
    updatedAt: '2026-07-14T12:30:00+05:00',
    comments: [
      {
        id: 'cmt-022',
        postId: 'post-011',
        userId: 'usr-106',
        userName: 'Zainab Malik',
        content:
          'The regen also weakens noticeably when the pack is cold, which catches people out on the descent. Do not assume you will recover as much coming back down as you spent going up.',
        likeCount: 29,
        createdAt: '2026-07-14T17:00:00+05:00',
      },
    ],
  },
  {
    id: 'post-012',
    slug: 'first-public-charger-in-faisalabad-is-live',
    userId: 'usr-114',
    userName: 'Rabia Anwar',
    userVehicle: 'MG HS PHEV',
    title: 'First public charger in Faisalabad is live',
    content:
      'It finally happened. A 60 kW CCS2 unit went live near the Kohinoor area this week — as far as I know the first public DC charger in Faisalabad.\n\nTried it yesterday. Pulled 54 kW steady, card payment worked, and the site is lit and staffed in the evening. Tariff is 72 per unit, which is in line with Lahore.\n\nSmall thing nationally, big thing here. Up to now the honest answer to anyone in Faisalabad asking about an EV was that they needed home charging and no intercity plans.',
    category: 'ev-news',
    likeCount: 142,
    commentCount: 37,
    createdAt: '2026-07-12T15:00:00+05:00',
    updatedAt: '2026-07-12T15:00:00+05:00',
    comments: [
      {
        id: 'cmt-023',
        postId: 'post-012',
        userId: 'usr-115',
        userName: 'Tahir Mehmood',
        content:
          'This is genuinely good news. Faisalabad to Lahore is only 127 km so this makes that route trivial in almost anything now.',
        likeCount: 31,
        createdAt: '2026-07-12T18:20:00+05:00',
      },
    ],
  },
]

// ─── EV Clubs ────────────────────────────────────────

export const MOCK_CLUBS: EVClub[] = [
  {
    id: 'club-001',
    name: 'Lahore EV Owners Club',
    city: 'Lahore',
    memberCount: 234,
    description:
      'The largest EV community in Punjab. Monthly meetups, group charging trips and a very active parts-and-service recommendation thread.',
    isJoined: false,
  },
  {
    id: 'club-002',
    name: 'Islamabad EV Community',
    city: 'Islamabad',
    memberCount: 178,
    description:
      'Capital-region owners covering Islamabad and Rawalpindi. Organises northern-areas convoys through the summer.',
    isJoined: false,
  },
  {
    id: 'club-003',
    name: 'Karachi Electric Riders',
    city: 'Karachi',
    memberCount: 156,
    description:
      'Karachi-wide group with a strong imported-EV contingent. Good place to ask about CHAdeMO and grey-import servicing.',
    isJoined: false,
  },
  {
    id: 'club-004',
    name: 'Rawalpindi EV Circle',
    city: 'Rawalpindi',
    memberCount: 89,
    description:
      'Smaller, practical group focused on home charging installs and shared workshop recommendations around the Pindi area.',
    isJoined: false,
  },
  {
    id: 'club-005',
    name: 'Faisalabad EV Group',
    city: 'Faisalabad',
    memberCount: 67,
    description:
      'Growing fast since the first public charger opened. Mostly first-time EV owners helping each other through the early months.',
    isJoined: false,
  },
  {
    id: 'club-006',
    name: 'Peshawar EV Drivers',
    city: 'Peshawar',
    memberCount: 45,
    description:
      'KP-based owners coordinating on the limited charging available and running an informal roadside-help roster.',
    isJoined: false,
  },
  {
    id: 'club-007',
    name: 'Multan EV Connect',
    city: 'Multan',
    memberCount: 38,
    description:
      'South Punjab group covering Multan and Bahawalpur. Focused on making the long runs north genuinely practical.',
    isJoined: false,
  },
  {
    id: 'club-008',
    name: 'Quetta EV Network',
    city: 'Quetta',
    memberCount: 29,
    description:
      'The newest club on Plug.pk. Small but determined, and the best source of information on charging in Balochistan.',
    isJoined: false,
  },
]

// ─── Platform Stats ──────────────────────────────────

export const MOCK_PLATFORM_STATS: PlatformStats = {
  totalStations: 250,
  totalCities: 18,
  totalUsers: 5000,
  totalReviews: 1200,
}

// ─── Signed-in User ──────────────────────────────────

export const MOCK_USER: User = {
  id: 'user-001',
  email: 'ahmed@example.com',
  name: 'Ahmed Khan',
  role: 'user',
  city: 'Lahore',
  joinedAt: '2024-10-15T00:00:00+05:00',
  vehicles: [
    {
      id: 'vehicle-001',
      userId: 'user-001',
      // BYD Atto 3 — the first entry in MOCK_EV_MODELS.
      evModel: MOCK_EV_MODELS[0] as EVModel,
      customName: 'My BYD',
      color: 'Pearl White',
      licensePlate: 'LEB-2481',
      isDefault: true,
    },
  ],
  // These must match real MOCK_STATIONS ids ('stn-…'), not 'station-…'.
  savedStations: ['stn-001', 'stn-002', 'stn-006'],
  savedRoutes: [],
}

export const MOCK_USER_REVIEWS: Review[] = [
  {
    id: 'urev-001',
    userId: 'user-001',
    userName: 'Ahmed Khan',
    userVehicle: 'BYD Atto 3',
    rating: 5,
    comment:
      'Pulled a genuine 142 kW on the main unit — 20 to 80 percent in just under half an hour. Attendant helped me line up the cable. Easily the best hub in Lahore right now.',
    date: '2026-07-24T14:20:00+05:00',
    helpfulCount: 31,
    isVerified: true,
  },
  {
    id: 'urev-002',
    userId: 'user-001',
    userName: 'Ahmed Khan',
    userVehicle: 'BYD Atto 3',
    rating: 4,
    comment:
      'Solid stop on the way back from Islamabad. The 120 kW unit held about 105 kW which is fine for a market break, though the bays are tight for anything longer than a hatchback.',
    date: '2026-07-08T17:45:00+05:00',
    helpfulCount: 12,
    isVerified: true,
  },
  {
    id: 'urev-003',
    userId: 'user-001',
    userName: 'Ahmed Khan',
    userVehicle: 'BYD Atto 3',
    rating: 5,
    comment:
      'Left the car on the 22 kW bay while I did the weekly shop and came back to 40 percent more. Cheapest per-unit rate I have found in Lahore and the bays are always free.',
    date: '2026-06-19T11:30:00+05:00',
    helpfulCount: 18,
    isVerified: false,
  },
]

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: 'act-001',
    type: 'review',
    text: 'You reviewed',
    highlight: 'Mall Road EV Hub',
    date: '2026-07-24T14:20:00+05:00',
  },
  {
    id: 'act-002',
    type: 'save',
    text: 'You saved',
    highlight: 'DHA Charging Hub',
    date: '2026-07-21T09:10:00+05:00',
  },
  {
    id: 'act-003',
    type: 'route',
    text: 'You planned a route from',
    highlight: 'Lahore to Islamabad',
    date: '2026-07-18T16:40:00+05:00',
  },
  {
    id: 'act-004',
    type: 'save',
    text: 'You saved',
    highlight: 'F-10 Charging Point',
    date: '2026-07-14T08:25:00+05:00',
  },
  {
    id: 'act-005',
    type: 'review',
    text: 'You reviewed',
    highlight: 'F-10 Charging Point',
    date: '2026-07-08T17:45:00+05:00',
  },
  {
    id: 'act-006',
    type: 'join',
    text: 'You joined',
    highlight: 'Lahore EV Owners Club',
    date: '2026-06-28T12:00:00+05:00',
  },
  {
    id: 'act-007',
    type: 'review',
    text: 'You reviewed',
    highlight: 'Gulberg Charging Station',
    date: '2026-06-19T11:30:00+05:00',
  },
  {
    id: 'act-008',
    type: 'join',
    text: 'You joined Plug.pk as an',
    highlight: 'EV owner',
    date: '2024-10-15T00:00:00+05:00',
  },
]

// ─── Business Portal ─────────────────────────────────

export const MOCK_BUSINESS: Business = {
  id: 'biz-001',
  userId: 'user-biz-001',
  name: 'Mall Road Premium Hotel',
  type: 'hotel',
  description:
    'A premium hotel in the heart of Lahore offering luxury accommodations and EV charging for guests. Covered bays, 24-hour security and a driver lounge with complimentary Wi-Fi.',
  address: {
    street: '24 Mall Road',
    area: 'Gulberg',
    city: 'Lahore',
    province: 'Punjab',
    country: 'Pakistan',
    postalCode: '54660',
  },
  coordinates: { lat: 31.5204, lng: 74.3587 },
  phone: '0300-1234567',
  email: 'info@mallroadhotel.pk',
  website: 'https://www.mallroadhotel.pk',
  photos: [],
  stations: [MOCK_STATIONS[0] as Station],
  rating: 4.7,
  reviewCount: 45,
  isVerified: true,
  isPremium: false,
  operatingHours: HOURS_24_7,
  createdAt: '2024-06-15T00:00:00+05:00',
}

export interface BusinessAnalyticsPeriod {
  profileViews: number
  navigateClicks: number
  reviewsReceived: number
  avgRating: number
}

export interface BusinessChartPoint {
  date: string
  views: number
  clicks: number
}

export interface BusinessReferrer {
  source: string
  count: number
  percent: number
}

export interface BusinessAnalytics {
  thisMonth: BusinessAnalyticsPeriod
  lastMonth: BusinessAnalyticsPeriod
  chartData: BusinessChartPoint[]
  topReferrers: BusinessReferrer[]
}

export const MOCK_BUSINESS_ANALYTICS: BusinessAnalytics = {
  thisMonth: {
    profileViews: 1240,
    navigateClicks: 89,
    reviewsReceived: 12,
    avgRating: 4.8,
  },
  lastMonth: {
    profileViews: 1002,
    navigateClicks: 74,
    reviewsReceived: 8,
    avgRating: 4.6,
  },
  // Fixed values, not Math.random() — a random module-scope array would
  // differ between the server and client renders and break hydration.
  chartData: [
  { date: '2026-07-01', views: 55, clicks: 4 },
  { date: '2026-07-02', views: 75, clicks: 6 },
  { date: '2026-07-03', views: 65, clicks: 5 },
  { date: '2026-07-04', views: 51, clicks: 3 },
  { date: '2026-07-05', views: 22, clicks: 1 },
  { date: '2026-07-06', views: 37, clicks: 4 },
  { date: '2026-07-07', views: 63, clicks: 5 },
  { date: '2026-07-08', views: 42, clicks: 3 },
  { date: '2026-07-09', views: 26, clicks: 2 },
  { date: '2026-07-10', views: 71, clicks: 7 },
  { date: '2026-07-11', views: 47, clicks: 3 },
  { date: '2026-07-12', views: 71, clicks: 4 },
  { date: '2026-07-13', views: 66, clicks: 6 },
  { date: '2026-07-14', views: 69, clicks: 4 },
  { date: '2026-07-15', views: 40, clicks: 3 },
  { date: '2026-07-16', views: 23, clicks: 1 },
  { date: '2026-07-17', views: 50, clicks: 4 },
  { date: '2026-07-18', views: 36, clicks: 3 },
  { date: '2026-07-19', views: 20, clicks: 2 },
  { date: '2026-07-20', views: 53, clicks: 4 },
  { date: '2026-07-21', views: 62, clicks: 6 },
  { date: '2026-07-22', views: 69, clicks: 4 },
  { date: '2026-07-23', views: 70, clicks: 5 },
  { date: '2026-07-24', views: 75, clicks: 4 },
  { date: '2026-07-25', views: 71, clicks: 5 },
  { date: '2026-07-26', views: 21, clicks: 2 },
  { date: '2026-07-27', views: 21, clicks: 1 },
  { date: '2026-07-28', views: 77, clicks: 5 },
  { date: '2026-07-29', views: 39, clicks: 3 },
  { date: '2026-07-30', views: 64, clicks: 5 },
  ],
  topReferrers: [
    { source: 'Map Search', count: 456, percent: 37 },
    { source: 'Direct URL', count: 312, percent: 25 },
    { source: 'Google', count: 248, percent: 20 },
    { source: 'Community', count: 136, percent: 11 },
    { source: 'Other', count: 88, percent: 7 },
  ],
}

/** Reviews shown in the business portal — the flagship station's reviews. */
export const MOCK_BUSINESS_REVIEWS: Review[] = MOCK_STATIONS[0]?.reviews ?? []
