// src/components/community/index.ts
export { CommunityHero } from './CommunityHero'
export { CategoryTabs, POST_ICON } from './CategoryTabs'
export { PostCard, Avatar, avatarGradient } from './PostCard'
export { PostFeed } from './PostFeed'
export { CreatePostForm } from './CreatePostForm'
export { CommunitySidebar } from './CommunitySidebar'
export { CommentSection } from './CommentSection'
export { ClubCard } from './ClubCard'
export { ClubsDirectory } from './ClubsDirectory'

export type { CommunityHeroProps } from './CommunityHero'
export type { CategoryTabsProps, CommunitySortOption } from './CategoryTabs'
export type { PostCardProps } from './PostCard'
export type { PostFeedProps } from './PostFeed'
export type { CreatePostFormProps } from './CreatePostForm'
export type { CommunitySidebarProps } from './CommunitySidebar'
export type { CommentSectionProps } from './CommentSection'
export type { ClubCardProps } from './ClubCard'
export type { ClubsDirectoryProps } from './ClubsDirectory'
