// src/components/admin/CarImageManager.tsx
'use client'

import { AlertTriangle, Check, ImageOff, Loader2, Trash2, Upload } from 'lucide-react'
import Image from 'next/image'
import { useRouter } from 'next/navigation'
import * as React from 'react'

import type { ImageCredit } from '@/data/carImageCredits'
import { setCarImage } from '@/lib/db/car-actions'
import { uploadCarPhoto } from '@/lib/db/upload-actions'
import { cn } from '@/lib/utils'

/**
 * The photograph on one car: replace it, or take it away.
 *
 * ── Two kinds of file, and the difference matters ──────────────────────
 *
 * A path under /images/cars came from the seed: 32 files fetched from Wikimedia
 * Commons, each with a licence and a photographer recorded in
 * src/data/carImageCredits.ts and regenerated by scripts/fetch-car-images.mjs.
 * A path under /uploads/cars was put there by a person through this control, and
 * has no licence on record.
 *
 * The panel says which is which, because the consequences differ. Replacing a
 * credited file leaves the credits module naming a photographer whose picture is
 * no longer on screen — CC BY-SA attribution pointing at the wrong image — so
 * that case gets warned about before the click rather than after.
 *
 * ── Upload and assignment are two steps on the server ──────────────────
 *
 * uploadCarPhoto stores the file and returns a path; setCarImage writes that
 * path onto the row. Separating them means a rejected file never touches the
 * car, and the row is only pointed at something that exists on disk. It also
 * means the old file is deleted by setCarImage after the new one is safely
 * written, never before.
 */

export interface CarImageManagerProps {
  carId: string
  carName: string
  image: string | null
  credit: ImageCredit | undefined
}

type Status = { kind: 'idle' } | { kind: 'busy'; label: string } | { kind: 'done'; message: string } | { kind: 'error'; message: string }

const MAX_MB = 5

/** A seeded, credited asset rather than something uploaded here. */
function isRepositoryAsset(path: string | null): boolean {
  return path !== null && path.startsWith('/images/')
}

export function CarImageManager({ carId, carName, image, credit }: CarImageManagerProps) {
  const router = useRouter()
  const inputRef = React.useRef<HTMLInputElement>(null)
  const [status, setStatus] = React.useState<Status>({ kind: 'idle' })
  const [preview, setPreview] = React.useState<string | null>(null)

  const busy = status.kind === 'busy'
  const seeded = isRepositoryAsset(image)

  // A local preview so the operator sees the file they chose before it is
  // committed, and so the panel is not blank while the request is in flight.
  React.useEffect(() => {
    return () => {
      if (preview) URL.revokeObjectURL(preview)
    }
  }, [preview])

  async function onFile(event: React.ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]
    if (!file) return

    // Checked here as well as on the server: a 40MB photo should be refused
    // before it is uploaded, not after.
    if (file.size > MAX_MB * 1024 * 1024) {
      setStatus({ kind: 'error', message: `That file is ${(file.size / 1024 / 1024).toFixed(1)}MB. The limit is ${MAX_MB}MB.` })
      event.target.value = ''
      return
    }

    setPreview(URL.createObjectURL(file))
    setStatus({ kind: 'busy', label: 'Uploading…' })

    const form = new FormData()
    form.set('file', file)

    const uploaded = await uploadCarPhoto(form)
    if (!uploaded.ok || !uploaded.url) {
      setStatus({ kind: 'error', message: uploaded.message ?? 'The upload failed.' })
      event.target.value = ''
      return
    }

    setStatus({ kind: 'busy', label: 'Saving…' })
    const assigned = await setCarImage(carId, uploaded.url)

    if (!assigned.ok) {
      setStatus({ kind: 'error', message: assigned.message ?? 'The file uploaded but could not be attached.' })
      event.target.value = ''
      return
    }

    setStatus({ kind: 'done', message: 'Photograph updated.' })
    event.target.value = ''
    router.refresh()
  }

  async function onRemove() {
    setStatus({ kind: 'busy', label: 'Removing…' })
    const outcome = await setCarImage(carId, null)

    if (!outcome.ok) {
      setStatus({ kind: 'error', message: outcome.message ?? 'Could not remove it.' })
      return
    }

    setPreview(null)
    setStatus({ kind: 'done', message: 'Photograph removed. The live card now shows a placeholder.' })
    router.refresh()
  }

  const shown = preview ?? image

  return (
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white">
      {shown ? (
        <div className="relative aspect-[16/10] bg-slate-100">
          {/* The preview is a blob URL, which next/image cannot optimise, so it
              renders as a plain img — the alternative is no preview at all. */}
          {preview ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img src={preview} alt="" className="absolute inset-0 h-full w-full object-cover" />
          ) : (
            <Image
              src={shown}
              alt={`${carName} — the photograph used on the live site`}
              fill
              sizes="(max-width: 1280px) 100vw, 360px"
              className="object-cover"
            />
          )}

          {busy ? (
            <div className="absolute inset-0 flex items-center justify-center gap-2 bg-slate-900/55 text-ui-sm font-semibold text-white">
              <Loader2 size={16} className="animate-spin" aria-hidden="true" />
              {status.label}
            </div>
          ) : null}
        </div>
      ) : (
        <div className="flex aspect-[16/10] flex-col items-center justify-center gap-2 border-b border-dashed border-slate-300 bg-slate-50 text-slate-400">
          {busy ? (
            <>
              <Loader2 size={22} className="animate-spin" aria-hidden="true" />
              <p className="text-ui-sm font-semibold">{status.label}</p>
            </>
          ) : (
            <>
              <ImageOff size={26} aria-hidden="true" />
              <p className="text-ui-sm font-semibold">No photograph</p>
              <p className="px-6 text-center text-ui-xs">The live card shows a placeholder.</p>
            </>
          )}
        </div>
      )}

      <div className="p-5">
        <h2 className="text-ui-sm font-bold uppercase tracking-[0.1em] text-slate-500">
          Photograph
        </h2>

        {status.kind === 'done' || status.kind === 'error' ? (
          <p
            role="status"
            aria-live="polite"
            className={cn(
              'mt-3 flex items-start gap-2 rounded-lg border p-2.5 text-ui-xs',
              status.kind === 'done'
                ? 'border-emerald-200 bg-emerald-50 text-emerald-800'
                : 'border-red-200 bg-red-50 text-red-800',
            )}
          >
            {status.kind === 'done' ? (
              <Check size={13} className="mt-0.5 shrink-0" aria-hidden="true" />
            ) : (
              <AlertTriangle size={13} className="mt-0.5 shrink-0" aria-hidden="true" />
            )}
            {status.message}
          </p>
        ) : null}

        {image ? (
          <dl className="mt-3 flex flex-col gap-2 text-ui-sm">
            <div>
              <dt className="text-slate-500">Current file</dt>
              <dd className="mt-0.5 break-all font-mono text-ui-xs text-slate-700">{image}</dd>
            </div>
            <div>
              <dt className="text-slate-500">Source</dt>
              <dd className="mt-0.5 font-medium text-slate-900">
                {seeded ? 'Repository asset, from the seed' : 'Uploaded through this portal'}
              </dd>
            </div>
            {credit ? (
              <div>
                <dt className="text-slate-500">Credit</dt>
                <dd className="mt-0.5 text-slate-900">
                  {credit.author} · {credit.licence}
                </dd>
              </div>
            ) : null}
          </dl>
        ) : null}

        {/*
          The warning that matters, shown before the click rather than after.
          Replacing a credited Commons file leaves carImageCredits.ts naming a
          photographer whose picture is no longer the one on screen, which is a
          licence problem rather than an untidy one.
        */}
        {seeded && credit ? (
          <p className="mt-3 flex items-start gap-2 rounded-lg border border-amber-200 bg-amber-50 p-2.5 text-ui-xs leading-relaxed text-amber-800">
            <AlertTriangle size={13} className="mt-0.5 shrink-0" aria-hidden="true" />
            <span>
              This file is credited to <strong>{credit.author}</strong> under {credit.licence}.
              Replacing it here leaves that credit attached to a photograph that is no longer shown
              — remove the entry from <code className="font-mono">carImageCredits.ts</code>, or
              re-run the fetch script, if you do.
            </span>
          </p>
        ) : null}

        <div className="mt-4 flex flex-wrap gap-2">
          <input
            ref={inputRef}
            type="file"
            accept="image/jpeg,image/png,image/webp"
            onChange={onFile}
            disabled={busy}
            className="hidden"
          />
          <button
            type="button"
            onClick={() => inputRef.current?.click()}
            disabled={busy}
            className="inline-flex h-10 items-center gap-2 rounded-lg bg-slate-900 px-4 text-ui font-semibold text-white transition-colors hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-slate-900 focus-visible:ring-offset-2"
          >
            <Upload size={15} aria-hidden="true" />
            {image ? 'Replace' : 'Upload'}
          </button>

          {image ? (
            <button
              type="button"
              onClick={onRemove}
              disabled={busy}
              className="inline-flex h-10 items-center gap-2 rounded-lg border border-slate-300 px-4 text-ui font-semibold text-slate-700 transition-colors hover:border-red-300 hover:bg-red-50 hover:text-red-700 disabled:cursor-not-allowed disabled:opacity-60 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400"
            >
              <Trash2 size={15} aria-hidden="true" />
              Remove
            </button>
          ) : null}
        </div>

        <p className="mt-3 text-ui-xs leading-relaxed text-slate-500">
          JPEG, PNG or WebP, up to {MAX_MB}MB. Landscape suits the cards, which crop to 16:10. The
          file type is checked from the file&apos;s own first bytes, not its name, and it is stored
          under a generated filename.
        </p>
      </div>
    </section>
  )
}
