// src/components/ui/icons/index.ts

/*
  One module per icon, re-exported here. The split is for the bundle.

  This was a single file holding all 137 icons, and webpack does not divide a
  module between pages: an export is "used" if any page anywhere uses it, and
  the module then ships whole to every page that imports anything from it.
  Measured against the same site drawn in Lucide, that put roughly 68 kB on
  every route. With each icon in its own module, and this folder marked free
  of side effects in its package.json, an import from here resolves straight
  to the modules a page names and nothing else.

  Imports do not change: `import { Search } from '@/components/ui/icons'`.
  To add an icon, add a file beside the others and a line below.
*/

export type { AppIconProps, IconType } from './adapt'

export { Activity } from './Activity'
export { AlertCircle } from './AlertCircle'
export { AlertTriangle } from './AlertTriangle'
export { ArrowDown } from './ArrowDown'
export { ArrowLeft } from './ArrowLeft'
export { ArrowRight } from './ArrowRight'
export { ArrowUpDown } from './ArrowUpDown'
export { ArrowUpRight } from './ArrowUpRight'
export { BadgeCheck } from './BadgeCheck'
export { Banknote } from './Banknote'
export { BarChart2 } from './BarChart2'
export { BarChart3 } from './BarChart3'
export { Battery } from './Battery'
export { BatteryCharging } from './BatteryCharging'
export { BatteryLow } from './BatteryLow'
export { Bed } from './Bed'
export { Bell } from './Bell'
export { Bookmark } from './Bookmark'
export { BookmarkCheck } from './BookmarkCheck'
export { Building } from './Building'
export { Building2 } from './Building2'
export { Cable } from './Cable'
export { Calendar } from './Calendar'
export { CalendarCheck } from './CalendarCheck'
export { CalendarClock } from './CalendarClock'
export { Camera } from './Camera'
export { Car } from './Car'
export { Check } from './Check'
export { CheckCircle2 } from './CheckCircle2'
export { ChevronDown } from './ChevronDown'
export { ChevronLeft } from './ChevronLeft'
export { ChevronRight } from './ChevronRight'
export { CircleSlash } from './CircleSlash'
export { Clock } from './Clock'
export { Coffee } from './Coffee'
export { Copy } from './Copy'
export { CornerUpRight } from './CornerUpRight'
export { Crosshair } from './Crosshair'
export { Database } from './Database'
export { DoorOpen } from './DoorOpen'
export { ExternalLink } from './ExternalLink'
export { Eye } from './Eye'
export { EyeOff } from './EyeOff'
export { FileQuestion } from './FileQuestion'
export { Filter } from './Filter'
export { Flag } from './Flag'
export { Flame } from './Flame'
export { Gauge } from './Gauge'
export { GitCompare } from './GitCompare'
export { GitCompareArrows } from './GitCompareArrows'
export { Globe } from './Globe'
export { Handshake } from './Handshake'
export { Heart } from './Heart'
export { HelpCircle } from './HelpCircle'
export { Home } from './Home'
export { Hotel } from './Hotel'
export { Image } from './Image'
export { ImageOff } from './ImageOff'
export { ImagePlus } from './ImagePlus'
export { Images } from './Images'
export { Inbox } from './Inbox'
export { Info } from './Info'
export { Layers } from './Layers'
export { LayoutDashboard } from './LayoutDashboard'
export { LayoutGrid } from './LayoutGrid'
export { LayoutList } from './LayoutList'
export { LifeBuoy } from './LifeBuoy'
export { Link } from './Link'
export { Link2 } from './Link2'
export { List } from './List'
export { ListFilter } from './ListFilter'
export { Loader2 } from './Loader2'
export { LocateFixed } from './LocateFixed'
export { Lock } from './Lock'
export { LogOut } from './LogOut'
export { Mail } from './Mail'
export { Map } from './Map'
export { MapPin } from './MapPin'
export { MapPinned } from './MapPinned'
export { Maximize2 } from './Maximize2'
export { Menu } from './Menu'
export { MessageCircle } from './MessageCircle'
export { MessageSquare } from './MessageSquare'
export { Minus } from './Minus'
export { Navigation } from './Navigation'
export { Navigation2 } from './Navigation2'
export { Newspaper } from './Newspaper'
export { Package } from './Package'
export { PanelLeftClose } from './PanelLeftClose'
export { PanelLeftOpen } from './PanelLeftOpen'
export { ParkingSquare } from './ParkingSquare'
export { PenSquare } from './PenSquare'
export { Pencil } from './Pencil'
export { Phone } from './Phone'
export { Plug } from './Plug'
export { PlugZap } from './PlugZap'
export { Plus } from './Plus'
export { Receipt } from './Receipt'
export { RefreshCw } from './RefreshCw'
export { RotateCcw } from './RotateCcw'
export { RotateCw } from './RotateCw'
export { Route } from './Route'
export { Save } from './Save'
export { Search } from './Search'
export { SearchX } from './SearchX'
export { Send } from './Send'
export { Settings } from './Settings'
export { Share2 } from './Share2'
export { Shield } from './Shield'
export { ShieldAlert } from './ShieldAlert'
export { ShieldCheck } from './ShieldCheck'
export { ShoppingBag } from './ShoppingBag'
export { ShoppingCart } from './ShoppingCart'
export { SlidersHorizontal } from './SlidersHorizontal'
export { Smartphone } from './Smartphone'
export { Snowflake } from './Snowflake'
export { Star } from './Star'
export { Store } from './Store'
export { Tag } from './Tag'
export { ThumbsUp } from './ThumbsUp'
export { Timer } from './Timer'
export { Trash2 } from './Trash2'
export { TrendingDown } from './TrendingDown'
export { TrendingUp } from './TrendingUp'
export { Trophy } from './Trophy'
export { Twitter } from './Twitter'
export { Undo2 } from './Undo2'
export { Upload } from './Upload'
export { User } from './User'
export { UserCircle } from './UserCircle'
export { UserPlus } from './UserPlus'
export { Users } from './Users'
export { Utensils } from './Utensils'
export { UtensilsCrossed } from './UtensilsCrossed'
export { Wifi } from './Wifi'
export { Wind } from './Wind'
export { Wrench } from './Wrench'
export { X } from './X'
export { XCircle } from './XCircle'
export { Zap } from './Zap'
