// src/data/carImageCredits.ts
//
// GENERATED by scripts/fetch-car-images.mjs — do not edit by hand.
//
// Every car photograph comes from Wikimedia Commons under a CC or public-domain
// licence. Most are CC BY-SA, which requires the photographer to be credited
// wherever the image appears, so this map exists to put that credit next to the
// photo rather than only in a file nobody opens.
//
// Regenerate with: node scripts/fetch-car-images.mjs

export interface ImageCredit {
  author: string
  licence: string
  licenceUrl: string | null
  /** The Commons file page, which carries the full licence terms. */
  source: string
}

export const carImageCredits: Record<string, ImageCredit> = {
  'byd-atto-2': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BYD_Atto_2_IAA_2025_DSC_2131.jpg",
  },
  'byd-atto-3-advanced': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BYD_Atto_3_1X7A6491.jpg",
  },
  'byd-seal': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2022_BYD_Seal.jpg",
  },
  'byd-sealion-6': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_BYD_Song_Plus_DM-i_(front).jpg",
  },
  'byd-sealion-7-advanced': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_BYD_Sealion_7_Performance_front.jpg",
  },
  'chery-tiggo-7-phev': {
    author: "JustAnotherCarDesigner",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Chery_Tiggo_7_II_014_(cropped).jpg",
  },
  'chery-tiggo-8-phev': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Chery_Tiggo_8_Plus_018_(cropped).jpg",
  },
  'chery-tiggo-9-phev': {
    author: "Make Chiffon great again",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Chery_Tiggo_9_01.jpg",
  },
  'deepal-e07': {
    author: "Chanokchon",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Deepal_E07_Performance_AWD.jpg",
  },
  'deepal-l07': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Chang%27an_Shenlan_SL03_(front).jpg",
  },
  'deepal-s05-reev': {
    author: "KitsuneDP",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Deepal_S05_004.jpg",
  },
  'deepal-s07': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Deepal_S07_IAA_2025_DSC_1894.jpg",
  },
  'dfsk-seres-3': {
    author: "Leongyy02",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Exterior_of_Seres_3,_Singapore,_5_April_2025.jpg",
  },
  'dongfeng-vigo': {
    author: "S5A-0043",
    licence: "CC BY 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: "https://commons.wikimedia.org/wiki/File:(SGP-Singapore)_Showcar_Dongfeng_Vigo_No-plate_2026-01-09.jpg",
  },
  'gugo-aion-v': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:GAC_Aion_V_(second_generation)_IAA_2025_DSC_1406.jpg",
  },
  'gwm-tank-300-hev': {
    author: "Anonymousfox36",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:TANK_300_IMG006.jpg",
  },
  'gwm-tank-500-phev': {
    author: "Anonymousfox36",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Tank_500_IMG001.jpg",
  },
  'haval-h6-hev': {
    author: "Zotyefan",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Haval_H6_III_IMG001_(cropped).jpg",
  },
  'haval-h6-phev': {
    author: "Zotyefan",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Haval_H6_III_IMG001_(cropped).jpg",
  },
  'haval-jolion-hev': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2020_Great_Wall_Haval_Jolion_(front).jpg",
  },
  'hyundai-ioniq-5': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Hyundai_Ioniq_5_AWD_Techniq-Paket_%E2%80%93_f_31122024.jpg",
  },
  'jaecoo-j6': {
    author: "Autosdeprimera",
    licence: "CC BY 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Jaecoo_J6_front_view.png",
  },
  'jaecoo-j7-phev': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Jaecoo_J7_1.6T_4WD_%E2%80%93_f_21032025.jpg",
  },
  'kia-ev5': {
    author: "iMoD Official",
    licence: "CC BY 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Kia_EV5_Earth_Exclusive_AWD_(Thailand)_front_view.png",
  },
  'kia-ev9-gt-line': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Kia_EV9_1X7A2472.jpg",
  },
  'mg-hs-phev': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:MG_HS_Hybrid%2B_Luxury_(II)_%E2%80%93_f_12032026.jpg",
  },
  'mg-zs-ev': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:MG_ZS_EV_Facelift_1X7A5867.jpg",
  },
  'omoda-7': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Omoda_7_SHS_IAA_2025_DSC_2186.jpg",
  },
  'omoda-e5': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_Chery_Omoda_E5_front.jpg",
  },
  'riddara-rd6': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2022_Radar_RD6_(front).jpg",
  },
  'toyota-corolla-cross-hev': {
    author: "Mr.choppers",
    licence: "CC BY-SA 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Toyota_Corolla_Cross_XLE_4WD_in_Wind_Chill_Pearl,_front_left.jpg",
  },
  'xpeng-g6': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:XPeng_G6_018_(cropped).jpg",
  },
}

/**
 * The credit for one car, or undefined if that car has no photograph.
 *
 * A function rather than letting callers index the map, so a car id with no
 * entry is a plain undefined at the call site rather than an unchecked lookup
 * that only fails once somebody renders it.
 */
export function getImageCredit(carId: string): ImageCredit | undefined {
  return carImageCredits[carId]
}
