// src/data/carImageCredits.ts
//
// GENERATED by scripts/fetch-car-images.mjs — do not edit by hand.
//
// Every car photograph comes from Wikimedia Commons under a CC or public-domain
// licence. Most are CC BY-SA, which requires the photographer to be credited
// wherever the image appears, so this map exists to put that credit next to the
// photo rather than only in a file nobody opens.
//
// Regenerate with: node scripts/fetch-car-images.mjs

export interface ImageCredit {
  author: string
  licence: string
  licenceUrl: string | null
  /** The Commons file page, which carries the full licence terms. */
  source: string
  /** What was done to the file, which CC BY-SA asks to be stated. Absent when it is used as published. */
  changes?: string
}

export const carImageCredits: Record<string, ImageCredit> = {
  'byd-atto-2': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BYD_Atto_2_IAA_2025_DSC_2131.jpg",
  },
  'byd-atto-3-advanced': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BYD_Atto_3_1X7A6491.jpg",
  },
  'byd-seal': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2022_BYD_Seal.jpg",
  },
  'byd-sealion-6': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_BYD_Song_Plus_DM-i_(front).jpg",
  },
  'byd-sealion-7-advanced': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_BYD_Sealion_7_Performance_front.jpg",
  },
  'chery-tiggo-7-phev': {
    author: "JustAnotherCarDesigner",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Chery_Tiggo_7_II_014_(cropped).jpg",
  },
  'chery-tiggo-8-phev': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Chery_Tiggo_8_Plus_018_(cropped).jpg",
  },
  'chery-tiggo-9-phev': {
    author: "Make Chiffon great again",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Chery_Tiggo_9_01.jpg",
  },
  'deepal-e07': {
    author: "Chanokchon",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Deepal_E07_Performance_AWD.jpg",
  },
  'deepal-l07': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Chang%27an_Shenlan_SL03_(front).jpg",
  },
  'deepal-s05-reev': {
    author: "KitsuneDP",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Deepal_S05_004.jpg",
  },
  'deepal-s07': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Deepal_S07_IAA_2025_DSC_1894.jpg",
  },
  'dfsk-seres-3': {
    author: "Leongyy02",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Exterior_of_Seres_3,_Singapore,_5_April_2025.jpg",
  },
  'dongfeng-vigo': {
    author: "S5A-0043",
    licence: "CC BY 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/4.0',
    source: "https://commons.wikimedia.org/wiki/File:(SGP-Singapore)_Showcar_Dongfeng_Vigo_No-plate_2026-01-09.jpg",
  },
  'gugo-aion-v': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:GAC_Aion_V_(second_generation)_IAA_2025_DSC_1406.jpg",
  },
  'gwm-tank-300-hev': {
    author: "Anonymousfox36",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:TANK_300_IMG006.jpg",
  },
  'gwm-tank-500-phev': {
    author: "Anonymousfox36",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Tank_500_IMG001.jpg",
  },
  'haval-h6-hev': {
    author: "Zotyefan",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Haval_H6_III_IMG001_(cropped).jpg",
  },
  'haval-h6-phev': {
    author: "Zotyefan",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Haval_H6_III_IMG001_(cropped).jpg",
  },
  'haval-jolion-hev': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2020_Great_Wall_Haval_Jolion_(front).jpg",
  },
  'hyundai-ioniq-5': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Hyundai_Ioniq_5_AWD_Techniq-Paket_%E2%80%93_f_31122024.jpg",
  },
  'jaecoo-j6': {
    author: "Autosdeprimera",
    licence: "CC BY 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Jaecoo_J6_front_view.png",
  },
  'jaecoo-j7-phev': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Jaecoo_J7_1.6T_4WD_%E2%80%93_f_21032025.jpg",
  },
  'kia-ev5': {
    author: "iMoD Official",
    licence: "CC BY 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Kia_EV5_Earth_Exclusive_AWD_(Thailand)_front_view.png",
  },
  'kia-ev9-gt-line': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Kia_EV9_1X7A2472.jpg",
  },
  'mg-hs-phev': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:MG_HS_Hybrid%2B_Luxury_(II)_%E2%80%93_f_12032026.jpg",
  },
  'mg-zs-ev': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:MG_ZS_EV_Facelift_1X7A5867.jpg",
  },
  'omoda-7': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Omoda_7_SHS_IAA_2025_DSC_2186.jpg",
  },
  'omoda-e5': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_Chery_Omoda_E5_front.jpg",
  },
  'riddara-rd6': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2022_Radar_RD6_(front).jpg",
  },
  'toyota-corolla-cross-hev': {
    author: "Mr.choppers",
    licence: "CC BY-SA 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Toyota_Corolla_Cross_XLE_4WD_in_Wind_Chill_Pearl,_front_left.jpg",
  },
  'xpeng-g6': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:XPeng_G6_018_(cropped).jpg",
  },
  // Added by hand, not by the fetcher: Audi and BMW photographs cut out onto
  // white to match the catalogue's studio shots. Regenerating with the fetcher
  // would drop these ten; carry them over. (The A6 e-tron photograph was
  // uploaded through the admin portal and carries no Commons credit.)
  'bmw-ix1': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:BMW_iX1_xDrive30_(U11)_%E2%80%93_f_05052024.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'bmw-ix2': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BMW_iX2_xDrive30_IMG_8425.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'bmw-ix3': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BMW_iX3_NA5_IAA_2025_DSC_1682.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'bmw-i4': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BMW_i4_IMG_6695.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'bmw-i5': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BMW_i5_1X7A1826.jpg",
    changes: "Background removed and set on white, mirrored; placard covered; plug.pk number plate added",
  },
  'bmw-ix': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_BMW_iX_DSC_2685.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'bmw-i7': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:BMW_i7_xDrive60_1X7A7476.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'audi-q6-e-tron': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Audi_Q6_e-tron_DSC_7829.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'audi-q8-e-tron': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Audi_Q8_e-tron_IAA_2023_1X7A0616.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'audi-e-tron-gt': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Audi_e-tron_GT_S_Auto_Zuerich_2024_DSC_6547.jpg",
    changes: "Background removed and set on white, mirrored; placard covered; plug.pk number plate added",
  },
  // The second catalogue expansion (September 2026), cut out in the same way.
  'mercedes-eqa': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_H243_(2023)_IMG_9000.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mercedes-eqb': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_X243_(2023)_IMG_2853.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mercedes-eqc': {
    author: "© M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_EQC_400_4MATIC_AMG_Line_(N_293)_%E2%80%93_f_02042021.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mercedes-eqs': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_V297_(2026%E2%80%93)_IMG_8833.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'mercedes-eqs-suv': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_X296_1X7A1725.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mercedes-glc-eq': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_GLC_with_EQ_Technology_IMG_7650.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mercedes-g580-eq': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_G_580_with_EQ_Technology_DSC_8256.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mercedes-c-class-electric': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mercedes-Benz_W520_IMG_8871.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'gwm-ora-03': {
    author: "M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:GWM_Ora_03_%E2%80%93_f_12102025.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'gwm-ora-05': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Ora_5_008.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'gwm-ora-07': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Ora_Lightning_Cat_004_(cropped).jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'haval-h6-gt-phev': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_Haval_H6GT_Ultra_front.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'gwm-tank-500-hev': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Great_Wall_TANK_500_Hi4-T.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'changan-nevo-hunter': {
    author: "Chanokchon",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_Deepal_Hunter_K50_REEV_Plus_AWD.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'changan-lumin': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2022_Chang%27an_Lumin_(front).jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'hyundai-tucson-hybrid': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Hyundai_Tucson_(NX4,_SWB)_Facelift_IMG_2344.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'hyundai-santa-fe-hybrid': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Hyundai_Santa_Fe_(TM)_PHEV_FL_IMG_0029.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'hyundai-elantra-hybrid': {
    author: "Damian B Oh",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Hyundai_Avante_Inspiration_CN7_PE_Cyber_Gray_Metallic_(front).jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'hyundai-palisade-hybrid': {
    author: "Damian B Oh",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Hyundai_Palisade_2.5T_Calligraphy_LX3_Creamy_White_Pearl_(46)_(cropped).jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'kia-sorento-phev': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Kia_Sorento_(MQ4)_Ditzingen_Mobil_IMG_9803.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'kia-sorento-hev': {
    author: "Benespit",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Kia_Sorento_MQ4_1.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'kia-sportage-l-hybrid': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_Kia_Sportage_SX_front.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'honda-hr-v-ehev': {
    author: "M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Honda_HR-V_e-HEV_Advance_Plus_(III,_Facelift)_%E2%80%93_f_30032025.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'nissan-sakura': {
    author: "Ohcock",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Nissan-Sakura-2026.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'mini-countryman-electric': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mini_Countryman_(U25)_IMG_9537.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mini-aceman': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mini_Aceman_DSC_7114.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mini-cooper-electric': {
    author: "Alexander-93",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Mini_Hatch_(J01)_Ditzingen_Mobil_IMG_9772_(cropped).jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'mg-cyberster': {
    author: "MrWalkr",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_MG_Cyberster.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mg-5-ev': {
    author: "Alexander Migl",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:MG_5_EV_(EP22)_1X7A6207.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'mg-zs-hybrid-plus': {
    author: "M 93",
    licence: "CC BY-SA 3.0 de",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0/de/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:MG_ZS_Hybrid%2B_Luxury_(II)_%E2%80%93_f_01012025.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'jetour-t1-i-dm': {
    author: "Zotyefan",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Jetour_Shanhai_T1_IMG001.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'jetour-t2-i-dm': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Jetour_Shanhai_T2_002.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'hyptec-ht': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:Hyptec_HT_003.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'icaur-v23': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:ICar_V23_005_(cropped).jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'icaur-v27': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:ICar_V27_003.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'jaecoo-j5-shs': {
    author: "CarsofGlasgow",
    licence: "CC BY 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_Jaecoo_5_1.6_Luxury_(United_Kingdom)_front_view.jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'chery-q': {
    author: "Ethan Llamas",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Chery_QEV_PIMS_2026_01.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'byd-shark-6': {
    author: "LuvsMG481",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2025_BYD_Shark_6_front.jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'xpeng-x9': {
    author: "JustAnotherCarDesigner",
    licence: "CC0",
    licenceUrl: 'http://creativecommons.org/publicdomain/zero/1.0/deed.en',
    source: "https://commons.wikimedia.org/wiki/File:XPeng_X9_003_(cropped).jpg",
    changes: "Background removed and set on white; number plate replaced with a plug.pk plate",
  },
  'xpeng-l03-reev': {
    author: "Tim Wu",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:XPeng_MONA_L03_in_Grandview_Mall,_Guangzhou_20260712.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'zeekr-009': {
    author: "JustAnotherCarDesigner",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:Zeekr_009_003.jpg",
    changes: "Background removed and set on white, mirrored; plug.pk number plate added",
  },
  'zeekr-x': {
    author: "User3204",
    licence: "CC BY-SA 4.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/4.0',
    source: "https://commons.wikimedia.org/wiki/File:2023_Zeekr_X_(front).jpg",
    changes: "Background removed and set on white, mirrored; number plate replaced with a plug.pk plate",
  },
  'haval-jolion-max-ev': {
    author: "iMoD Official",
    licence: "CC BY 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Haval_Xiaolong_BEV_front_view.png",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
  'rolls-royce-spectre': {
    author: "Mr.choppers",
    licence: "CC BY-SA 3.0",
    licenceUrl: 'https://creativecommons.org/licenses/by-sa/3.0',
    source: "https://commons.wikimedia.org/wiki/File:2024_Rolls-Royce_Spectre_in_Midnight_Sapphire_over_Silver,_front_left.jpg",
    changes: "Background removed and set on white; plug.pk number plate added",
  },
}

/**
 * The credit for one car, or undefined if that car has no photograph.
 *
 * A function rather than letting callers index the map, so a car id with no
 * entry is a plain undefined at the call site rather than an unchecked lookup
 * that only fails once somebody renders it.
 */
export function getImageCredit(carId: string): ImageCredit | undefined {
  return carImageCredits[carId]
}
